### ISSUE TITLE
Bouncy Castle PGP compatibility

### ISSUE THREAD

**Issue by vittogiothedon** [openpgpjs/openpgpjs#1034]
I am not able to decrypt a key generated by BCPGP (Version: BCPG C# v1.6.1.0), while i am able to do it with other tools. 
The same is happening when i try to encrypt a file, by using a public key, Version: BCPG C# v1.6.1.0.
the receiver is saying that the file has not been encrypted with the provided key.

Are there any setting i need to apply ?
i am using: 
Node.js v12.14.1
OpenPGP.js v4.8.0

Thank you for your advice

**Comment by SalvatoreMeschini** [comment]
Same issue here... 

Everything works as expected with the same keys/passphrase using other tools (e.g. PGPTool) to encrypt/decrypt data.

But using openpgpjs, we obtain: "*UnhandledPromiseRejectionWarning: Error: Unsupported legacy encrypted key*".

Is there a list formats/algorithms supported by openpgpjs or a way to test the compatibility of those keys with openpgpjs?

**Comment by twiss** [comment]
Hey :wave: This is due to the key using an old 16-bit hash rather than a SHA1 hash (or AEAD, but I don't think BCPGP supports that yet). I found the following parameter [here](https://borelly.net/cb/docs/javaBC-1.4.8/pg/org/bouncycastle/openpgp/PGPKeyRingGenerator.html):
> useSHA1 - checksum the secret keys with SHA1 rather than the older 16 bit checksum.

If you're using that function, that should be true. It even says

> **Deprecated.** _use method taking PBESecretKeyDecryptor_
>
> Create a new key ring generator using old style checksumming. It is recommended to use SHA1 checksumming where possible.

So - please use [that function](https://www.borelly.net/cb/docs/javaBC-1.4.8/pg/index.html?org/bouncycastle/openpgp/operator/PBESecretKeyEncryptor.html) instead, with a high S2K count, if possible.

---

> the receiver is saying that the file has not been encrypted with the provided key.

Could you post an example message and public key?

**Comment by vittogiothedon** [comment]
i made a test. Everything works fine if i encrypt/decrypt where the public key/passphrase are generated with the following algorithm: SHA256 with DSA 2048bit.
The public key i received has been made with SHA1 with RSA 2048bit. How may i force openpgp to use  SHA1 with RSA 2048bit to encrypt and decrypt?

**Comment by twiss** [comment]
OpenPGP.js automatically uses RSA if it specified in the key and message to encrypt and decrypt.

For SHA1, you could try setting `openpgp.config.prefer_hash_algorithm = openpgp.enums.hash.sha1;` before generating your own key and then encrypt a message. However, please keep in mind that SHA1 has been broken and this is insecure. The latest draft spec says:

> Implementations SHOULD NOT create messages which require the use of SHA-1 

Let me know if that fixes your issue. Also, if it turns out that it doesn't, please change it back again and delete that key with SHA1 in the preferences :)

**Comment by vittogiothedon** [comment]
Unfortunately it does not. I cannot use a different public key as it is the one that has been provided.
Here the code i use to encrypt (mainly form openpgp doc). As result of passing the public key (SHA1, RSA 2048), the receiver is saying: Invalid Encryption. if i use the same in C#, it is validating.

    const openpgp = require('openpgp')
    const fs = require('fs')
    openpgp.config.prefer_hash_algorithm = openpgp.enums.hash.sha1;
    openpgp.initWorker({ path:'openpgp.worker.js' })
    
// put keys in backtick (``) to avoid errors caused by spaces or tabs
const pubkey = `-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.56
key...
key...
-----END PGP PUBLIC KEY BLOCK-----`

const encryptDecryptFunction = async() => {
    const file = fs.readFileSync('C:\\Users..').toString();
    const options = {
        message: openpgp.message.fromText(file),       // input as Message object
        publicKeys: (await openpgp.key.readArmored(pubkey)).keys
    }
    openpgp.encrypt(options).then(ciphertext => {
        encrypted = ciphertext.data // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'
        console.log(encrypted);
        fs.writeFileSync('C:\\Users..', encrypted);
        return encrypted
  })
}
encryptDecryptFunction()

**Comment by twiss** [comment]
> the receiver is saying: Invalid Encryption

What program / library is receiver running? Could you ask them to generate another example private key and send it to us, and send us the command or code they're running that's causing this error?
