### ISSUE TITLE
Key decrypted, despite failed Promise

### ISSUE THREAD

**Issue by pbrunschwig** [openpgpjs/openpgpjs#1048]
I have a weird issue with decrypting keys: I run the following code with privateKey set to my regular (production) key 0xDB1187B9DD5F693B:

    await privateKey.decrypt(passphrase);

This throws the following exception:

    TypeError: "this.s2k is null"
    decrypt chrome://enigmail/content/modules/stdlib/openpgp-lib.js:39633
    results chrome://enigmail/content/modules/stdlib/openpgp-lib.js:34099
    results chrome://enigmail/content/modules/stdlib/openpgp-lib.js:34097
    decrypt chrome://enigmail/content/modules/stdlib/openpgp-lib.js:34094

But yet, if I wait for a moment, `privateKey` is decrypted and can be used to sign or decrypt messages.

Line numbers refer to the non-minimized dist/openpgp.js file, version 4.9.0.

**Comment by tomholub** [comment]
What is the structure of the key you are decrypting? It may be possible that some key packets got decrypted while one of them threw an error, leaving the actual key object in a mixed state.

**Comment by pbrunschwig** [comment]
It's a pretty large key with several subkeys:
* primary key: RSA 4096, created 2015, expires in 2025
* encryption subkey RSA 4096, created 2015, expired in 2018
* encryption subkey RSA 4096, created 2018, expires in 2022

2 user IDs and a photo.

**Comment by twiss** [comment]
Hey :wave: Yeah, this can happen when one of the (sub)key packets can't be decrypted, but others can. This was also discussed in https://github.com/openpgpjs/openpgpjs/issues/945. In v5, we'll make the function return either an error or a fully decrypted clone of the key, because I agree the current behavior is super weird.

For this specific error, my guess is that the subkey was encrypted with unsalted MD5 as its "S2K" (the last option described here: https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-08#section-3.7.2.1). As far as I can tell, support for this has been broken in OpenPGP.js for a long time, and explicitly removed in https://github.com/openpgpjs/openpgpjs/pull/1029, although the error message could be better. To fix the key for OpenPGP.js, you could simply remove the subkey, or re-encrypt it with an S2K.

(Alternatively, the subkey could just be corrupted. It's a little difficult to tell without an encrypted private key.)

**Comment by pbrunschwig** [comment]
Yes, this explains. I re-encrypted the key with an S2K, and now it works fine.

**Comment by tomholub** [comment]
> and explicitly removed in #1029, although the error message could be better. 

Maybe error message such as: **Deprecated S2K algorithm: simple MD5. Please update key to use a modern S2K**
