### ISSUE TITLE
npm packages are being skipped

### ISSUE THREAD

**Issue by ardimaunahan** [openpgpjs/openpgpjs#1049]
In my `npm install`, can anyone explain the warnings here and how can they be fixed? 
![photo_2020-02-21_19-41-44](https://user-images.githubusercontent.com/673492/75031915-4aa6aa00-54e2-11ea-9215-d9adfc9092fc.jpg)

Note that it is blocking my application build (using webpack) due to missing libraries.
![photo_2020-02-21_19-45-00](https://user-images.githubusercontent.com/673492/75032095-b0933180-54e2-11ea-8bb2-058dc19b0294.jpg)

Any help would be highly appreciated.

**Comment by twiss** [comment]
Hey :wave: Probably this means your installation of git doesn't support cloning over ssh, for some reason.

However, please note that even if you get this working, building using webpack is not officially supported currently, and you might run into more issues. This will hopefully be fixed in v5. See #547, for example.

For now, I'd recommend just using a separate pre-built version of openpgp.js from the `dist` folder, if you can.

**Comment by ardimaunahan** [comment]
@twiss Thanks for the quick response. So it's git related. I'll check my git installation.

Note that I tried different machines too and I was able to do a successful install and build
![photo_2020-02-21_20-12-10](https://user-images.githubusercontent.com/673492/75033707-76c42a00-54e6-11ea-93c2-b396affe145b.jpg)

**Comment by twiss** [comment]
:+1: That's good to know. The build probably contains a bunch of unneeded dependencies that should be external, though; 778 KiB seems excessive (if it's minified). Not sure if that matters for your use case, ofc.

The issue might be that you might need to be logged in to github (i.e. have a valid ssh certificate on your device that you've uploaded to github); I've heard that github doesn't allow anonymous ssh connections. Why npm doesn't try to git clone over https, I don't know.

**Comment by ardimaunahan** [comment]
Forgot to mention that this has been closed. It is caused by not installing git in my teammate's environment.
