### ISSUE TITLE
Unable to verify messages with charset != UTF-8

### ISSUE THREAD

**Issue by pbrunschwig** [openpgpjs/openpgpjs#1064]
Many mails are (still) encoded in various character sets such as Latin1 (ISO-8859-15) or BIG5 (Japanese). I haven't found  a way to verify such messages with OpenPGP.js. 

I roughly do the following:

```javascript
  var msg = await openpgp.cleartext.readArmored(msgData);
  var verified = await openpgp.verify({
        message: msg,
        publicKeys: pubKeys
    });
```

This works fine with UTF-8 encoded data, but not with anything else. GnuPG verifies the message successfully.

Attached is a sample message that is encoded in Latin1, together with the key needed to verify the message. I created a ZIP such that the encoding wouldn't change during submission.

[msg.zip](https://github.com/openpgpjs/openpgpjs/files/4355888/msg.zip)

**Comment by tomholub** [comment]
Tested in our product (we use OpenPGP.js), appears to suffer from the same issue.

We are missing a `openpgp.cleartext.readBinary` or similar method, that doesn't force you to convert to a string which is always utf8 in javascript.

You may be able to debug this by composing the message object by hand, by using `message = openpgp.message.readBinary` and then `message.appendSignature('-----BEGIN PGP SIG...')`. If you can make it verify that way, you may be able to contribute a `openpgp.cleartext.readBinary` method or similar, too.

**Comment by twiss** [comment]
I think that even if you try that, it won't verify because of the following code, during verification of text signatures: https://github.com/openpgpjs/openpgpjs/blob/69f14023f28920c1b2ea61d72945d071a9c58253/src/packet/signature.js#L579-L585 So probably, we would have to change that to use `data.getBytes(true)` instead, and then canonicalize line endings on the binary data (because of https://tools.ietf.org/html/rfc4880#section-5.2.1 -> 0x01), which is a bit annoying but not impossible.

**Comment by pbrunschwig** [comment]
You're quite correct. This doesn't currently verify, even if I pass a Uint8Array.
