### ISSUE TITLE
Can not lookup key

### ISSUE THREAD

**Issue by MalteKiefer** [openpgpjs/openpgpjs#1143]
Hi

I try to look up a key like this:

```javascript
		var hkp = new openpgp.HKP('https://' + keyserver);

		var options = {
		    query: mail
		};

		hkp.lookup(options).then(function(key) {
		    var pubkey = openpgp.key.readArmored(key);
				savekey(mail, pubkey, '');
		});
		console.log(pubkey);
		});
```
But there is not error message and not key. Nothing.
What did I wrong?

**Comment by tomholub** [comment]
Hello,

`console.log(pubkey);` executes first, and then the `var pubkey = openpgp.key.readArmored(key);` executes after. That's why you are seeing undefined. Move the `console.log` right after the above mentioned line, and you'll see the content.

This is not so much to do with the library, but rather how JavaScript promises executes. The execution order is not necessarily sequential the way you would expect synchronous code to execute.

**Comment by tomholub** [comment]
Alternatively there may be an error, for which a promise `.catch` statement with a log will be able to capture it.

**Comment by MalteKiefer** [comment]
I do it like this:

```javascript
		hkp.lookup(options).then(function(key) {
		    var pubkey = openpgp.key.readArmored(key);
				console.log(pubkey);
				savekey(mail, pubkey, '');
		}).catch(function(err){
			console.log(err);
		});
```

still no output.

**Comment by wiktor-k** [comment]
@MalteKiefer try:

```js
var hkp = new openpgp.HKP('https://keys.openpgp.org');

var options = {
 query: "look@my.amazin.horse"
};

hkp.lookup(options).then(key => openpgp.key.readArmored(key)).then(({keys}) => {
  console.log(keys);
});
```
