### ISSUE TITLE
Convenient methods to query the key for capabilities and other information

### ISSUE THREAD

**Issue by alichry** [openpgpjs/openpgpjs#1243]
When working with keys, users might find it convenient to use built-in functions in the OpenPGPjs library for some use cases:

1. Determine the key capabilities by inspecting the direct or binding signature. This method would return either the flag in the signature, or an array of `enum.keyFlag` for each set bit.
2. Get the latest direct or binding signature directly to make it easy for users trying to call low-level methods of OpenPGPjs.
3. Methods to indicate whether a key can be used for encryption or signing, e.g. `canEncrypt` and `canSign` regardless of the validity of the key. 
4. Get the primary key's user ids in the form of `{ name, email, comment }`. i.e. returning the userid packets directly, if data corruption might be an issue since the objects are returned, we can create a new object.

I have written some workarounds to achieve the above, but I believe it would be helpful to have some of those methods provided natively. Now, I would like to say that I am not an expert in OpenPGP(js)?, so please bear with me if some of the implications I made are incorrect 😊

I would be happy to submit a PR to fulfill a subset of these convenient functions.

Related issue: https://github.com/FlowCrypt/flowcrypt-browser/issues/3444

**Comment by tomholub** [comment]
> Determine the key capabilities by inspecting the direct or binding signature. This method would return either the flag in the signature, or an array of enum.keyFlag for each set bit.

This would be very useful for us too

> Get the primary key's user ids in the form of { name, email, comment }. i.e. returning the userid packets directly, if data corruption might be an issue since the objects are returned, we can create a new object.

I think there was some util method in OpenPGP.js addressing this?

**Comment by twiss** [comment]
Hey :wave:
Re. FlowCrypt/flowcrypt-browser#3444: I would rather this be solved with a set of config options indeed, rather than methods to query information about subkeys and then selecting a subkey (even though we now indeed do support the latter):

1. We already have `config.minRsaBits`, IMO it could be extended to also control usage of existing keys, not just key generation
2. For public-key algorithms, I would actually be open to have a blacklist of algorithms (similar to [`config.rejectHashAlgorithms`](https://github.com/openpgpjs/openpgpjs/blob/e1307b88d0b96ff7656d00310e0ccd5f05b25dcc/src/config/config.js#L211). IMO it should include DSA and ElGamal keys at this point (c.f. https://gitlab.com/sequoia-pgp/sequoia/-/issues/521)
3. For symmetric-key algorithms, we can already always use AES for encryption (https://github.com/openpgpjs/openpgpjs/discussions/1218)

Let me know if that would cover most of your use case. PRs are welcome :blush: And/or feel free to open separate issues for the first two. I'll respond to some of the specific proposals here in the PR.

**Comment by tomholub** [comment]
> We already have config.minRsaBits, IMO it could be extended to also control usage of existing keys, not just key generation

That would be amazing

> For public-key algorithms, I would actually be open to have a blacklist of algorithms (similar to config.rejectHashAlgorithms. IMO it should include DSA and ElGamal keys at this point (c.f. https://gitlab.com/sequoia-pgp/sequoia/-/issues/521)

Same, this would be great!

> For symmetric-key algorithms, we can already always use AES for encryption (#1218)

:+1:

**Comment by alichry** [comment]
https://github.com/openpgpjs/openpgpjs/pull/1250
