### ISSUE TITLE
Integrate fast ECC support

### ISSUE THREAD

**Issue by AlexanderWillner** [openpgpjs/openpgpjs#26]
See http://eprint.iacr.org/2011/654

**Comment by jonnybarnes** [comment]
Has ECC been implemented yet?

**Comment by fpietrosanti** [comment]
Also KBPGP from Keybase.io implement ECC https://github.com/keybase/kbpgp . 

What if we collect a sum $X to get ECC support implemented and integrated into OpenPGP.js code?

**Comment by tanx** [comment]
We talked about ECC alot at the [OpenPGP summit](https://gnupg.org/blog/20150426-openpgp-summit.html) in April. There were some concerns about compatibility but overall everyone agreed it's an inevitable step in the right direction. Especially in light of the web platform and performance when compared to RSA.

I see two options going forward...


1.) We all rally behind one OpenPGP JavaScript implementation like the native code community does for GPG. There is no particular reason to have multiple PGP JS libs which each need to be maintained and audited.

Whiteout is thinking about adopting the End-to-End lib because of ECC, its clean code and the resources Google is putting behind security audits and bounty. But we still have some reservations.

First of all the OpenPGP.js community is small but a very helpful, friendly and productive one. If there something that needs to change in the code I have a quick discussion with @toberndo over hangout and we make a decision. This allows us to quickly add new features or clean up legacy code e.g. like when we migrated to ES6 promises. OpenPGP.js has been audited twice by Cure53 and it's being used in production by Deutsche Telekom and 1&1 in Mailvelope/DEmail which means that not only Whiteout relies on stability and security. This is a great way to share the costs.

The full E2E PGP solution is not in production yet and it's not clear when it will. I talked with the Google developers quite a bit about their workflow internally and their willingness to accept community contributions. From what I gathered it seems that the master branch that is exposed to the github repository lags behind the upstream the Googlers work on internally. Changes are pushed to github regularly but with some delay as their internal review process is quite thorough. This has the obvious upside that the code quality is very very high, but it's also not obvious how outside contributions would fit into this process.

Another thing the devs also made clear is that they currently cannot split the lib into it's own GitHub repo due to other internal workflow constraints.

In terms of maturity the E2E library is being used in a number of production use cases internally and the team was very confident to recommend it for third party apps. Although as mentioned... The full PGP stack is not yet in production and from my experience this is where to most maintenance and interoperabilty work is.

If we go with E2E we (Whiteout) don't want to do that alone. We would probably only do it if Mailvelope is also willing to migrate.


2.) The second option would be to integrate the ECC modules from E2E into OpenPGP.js as was discussed above. The solution is the most straightforward but OpenPGP.js is already a mashup of js crypto code gathered from all over the internet. This would probably reduce consistency in the codebase even more. This is also not trivial and no one has raised their hand to handle the actual work and pay for an audit.


So those are the two options I see. We're going to try a proof of concept for integrating E2E lib in Whiteout once we find the time. Then we'll have more insight to share. Until the I'd like to get a feeling for the other OpenPGP.js users... What are you in favor of?

**Comment by fpietrosanti** [comment]
@tanx i think that diversity is important in the opensource ecosystem, not only in the code but also in the way specific projects get used or focus on.

As you say E2E have a set of bureaucracy  around it given the google internal constraints:
- cannot be spitted into a lib
- it's not updated immediately on github but there's a synchronization process between internal development and opensource release
- there could be issues in contribution and collaboration

From my point of view those are important enough constraint to let me skip using it as-it-is. 

A project like GnuPG or OpenPGP.js, with it's own diversity of management, diffusion and contributors, have a quite free-community oriented approach, without backing from a major multinational (that we love for it's opensource commitment, but impose rules limiting freedom a bit).

I am wondering if we could not think about "re-using" some of the Google E2E components in order to cleanup / bring consistency in the crypto being used within OpenPGP.js, but keeping it's independency?

From a software engineering point of view does it make sense for how OpenPGP.js is done?

If i understood properly, if @tanx and @toberndo switch to e2e for whiteout and mailvelope most current code contribution to openpgp.js would go away, bringing the project to a point where there's no active development? 

If so, would it help defining a roadmap and make it financed?

We could approach some funding (Like www.opentechfund.org) to ask for financing growth of the OpenPGP.js library itself, it would make a lot of sense given it's dependency with mailvelope and globaleaks, both funded by OTF?

**Comment by fxa** [comment]
Do we really need a full blown ECC implementation in openpgp.js?
Wouldn't it be enough to start with Berstein's curve25519?
There is a super fast implementation in C, see curve25519-donna, which
could be ported to js (actually I started with that some time ago but
did not finish)
And please, don't use the Weierstrass form for curve25519, that would
kill all the performance!

**Comment by fpietrosanti** [comment]
@fxa i agree that being minimalistic in the implementation of GnuPG compatible-only ECC support is the way to go, but the issues being presented is wider than just implementation of ECC, but it's more like if OpenPGP.js have a future or not

**Comment by tanx** [comment]
@fxa that sounds reasonable. Also see:

http://stackoverflow.com/questions/20961473/curve25519-implementation-for-javascript

**Comment by tanx** [comment]
> but it's more like if OpenPGP.js have a future or not

Sorry, I didn't mean to alarm anyone. Just trying to find a pragmatic way forward in an open forum. Just to clarify... Whiteout has not given up on OpenPGP.js. Quite the contrary, we're adding new features and having Cure53 review them as we speak (see https://github.com/openpgpjs/openpgpjs/pull/309). We're also using it in production and are very happy on the WebKit platforms (Chrome App, iOS, Android) since they offer native RSA keygen via WebCrypto. It's just that WebCrypto is not supported on all platforms.

**Comment by diafygi** [comment]
I agree with @fpietrosanti that a neutral, non-project-attached OpenPGP library is important. The E2E implementation is focused on end-to-end encrypted communication, not the OpenPGP format. So, it's very possible that the direction/development of that project could leave out or ignore other use cases such as package signing.

Also, back on the topic of this issue. I've been [playing around with](https://github.com/diafygi/openpgp-python/blob/master/openpgp.py#L1657) the OpenPGP format specifics for ECC keys, and I should be able to add the ability to read ECDSA and EdDSA keys. However, I don't yet have the ability to actually be able to sign and verify using those keys. Would likely have to copy the implementations from E2E for the actual signing/verifying.

Finally, what's all the talk about Curve25519? Is there a draft spec that adds curve25519 to the OpenPGP format? So far as I know, only [Ed25519](https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-02) has a spec.

**Comment by tanx** [comment]
> I agree with @fpietrosanti that a neutral, non-project-attached OpenPGP library is important.

That makes sense. It's good to get an impression of what the overall opinion is on this.

> Finally, what's all the talk about Curve25519? Is there a draft spec that adds curve25519 to the OpenPGP format?

Werner Koch should be able to explain everything in detail on thr GnuPG mailing list (or perhaps it already is in the list archive). It's probably best to use that as a reference when in doubt about the specs.

**Comment by fxa** [comment]
Sorry for introducing the curve25519 discussion,
but the main problem with ECC is, which curves do we trust?
Probably not the NIST/NSA curves.
The curve25519 has the advantage , that the c implementation of
curve25519-donna (64bit code) has only 450 lines of code without any
dependency, especially no big int lib is used.
So WHEN using ECC, curve25519 is a favourite candidate to start with

ps: I don't like ECC at all, because you have to trust in the curves
used. With RSA all is clear, if you want to break it, you have to do
factorisation, which is hard. But with ECC you never know, if the curve
has an back door. (QA on 31c3, Q: how can I know, you didn't introduce a
back door to your curve? A (Bernstein): you cannot, just trust in me!)

**Comment by barrydegraaff** [comment]
About the E2E code, I looked into it and it seems far from completion, that is also more or less stated on the E2E wiki.

I did some tests with key generation, and it seems fast in both Chrome and Firefox, but the code is not finished enough for good testing.

It is unclear to me if this library is meant to be something other then a part of a Chrome extension. The wiki talks about Chrome extension, more than OpenPGP JS lib.

To explain further, when I look at the e2e.openpgp object it has methods like:
ClearSignMessage: function $e2e$openpgp$ClearSignMessage$($body$$, $signatureBytes$$, $opt_hash$$) {
and
keygenerator: Object
jwkToNative_: function $e2e$openpgp$keygenerator$jwkToNative_$($jwkKey$$) {
newEcdhWithP256: function $e2e$openpgp$keygenerator$newEcdhWithP256$($key$$117_opt_privateKey$$) {
newEcdsaWithP256: function $e2e$openpgp$keygenerator$newEcdsaWithP256$($key$$116_opt_privateKey$$) {
newWebCryptoRsaKeys: function $e2e$openpgp$keygenerator$newWebCryptoRsaKeys$($keyLength$$) {

A cryptic crypto library? As an integrator I much prefer the OpenPGP.js approach:
signClearMessage: function signClearMessage(privateKeys, text) {
and
generateKeyPair: function generateKeyPair(options) {

So while E2E may be a good alternative some day, I hope that OpenPGP.js stays alive as a project as well. And that development on the OpenPGP.js project continues. 

Also already stated by others, the E2E code has hard dependencies to other Google Libraries (closure lib), Including these libraries may be a problem (technically and legally) in the project I am working on.

For the rest I tend to agree with I agree with @fpietrosanti .

Barry

Zimbra OpenPGP Zimlet
OpenPGP message extension for Zimbra Collaboration Suite.
https://github.com/barrydegraaff/pgp-zimlet

**Comment by emansipater** [comment]
Just chiming in here with what I hope is a helpful contribution.  I'm the CTO of KryptoKit and we're big fans of OpenPGPjs who are very interested in Elliptic Curve support, so we've started writing some.  In the blockchain community the curve we're already reliant on is secp256k1, which we know isn't as widely used by others.  Still, we hope our contributions will be useful to the library, and we'll be using libgcrypt's secp256k1 as our metric for interoperability.  We've budgeted for extensive tests and a professional audit to make sure we do it right.  Secp256k1 support will be very useful to us in an upcoming project, and we hope that even if it isn't exactly the most popular curve it will be a benefit to other library users as well.

It's still early stages, but you can follow our progress at https://github.com/Jaxx-io and we're happy to hear any feedback on how our contribution can be made most useful.

**Comment by fpietrosanti** [comment]
@emansipater Please consider integrating an ECC implementation that has been already audited, we may integrated the Google's End-to-End one?

**Comment by emansipater** [comment]
@fpietrosanti consensus above seemed to be that E2E integration was the poorer option, and it doesn't contain secp256k1 support anyways.  Instead, we're mirroring the heavily audited libsecp256k1 from Bitcoin, and also ensuring interoperability against libgcrypt.

**Comment by evilaliv3** [comment]
@emansipater do you have any update on this?

**Comment by tanx** [comment]
I'd like to suggest integrating just Curve25519 first. WhisperSystems' Signal Chrome App seems to compile a native C impl to JS. We could reuse that code and ask them if they're OK with relicensing to LGPL:

https://github.com/WhisperSystems/Signal-Desktop/tree/master/native

**Comment by barrydegraaff** [comment]
@tanx looks like the best suggestion so far +1

**Comment by tanx** [comment]
Looks like Curve25519 might be added to WebCrypto:

https://www.w3.org/2012/webcrypto/WebCryptoCurve25519/Curve25519-WebCrypto.html

But in the meantime an asm.js/wasm compile definitely makes sense.

**Comment by tanx** [comment]
Created two seperate issues to track both NIST Curves and Curve25519 support:
https://github.com/openpgpjs/openpgpjs/issues/427
https://github.com/openpgpjs/openpgpjs/issues/428

Closing this...
