### ISSUE TITLE
No method getPrimaryUser when encrypting with public key

### ISSUE THREAD

**Issue by unusualbob** [openpgpjs/openpgpjs#297]
I recently attempted to use this module and got an error when I tried to encrypt a simple string with my own public key. It's possible this is user error, but so far as I can tell my code matches the readme example.

Code:

``` javascript
var pubkeyFile = fs.readFileSync('/myPubkey.asc'); //GPG keychain exported public key
var pubkey = openpgp.key.readArmored(pubkeyFile.toString());
openpgp.encryptMessage(pubkey.keys, '1234567890', function(message) {
  console.log(message);
}).catch(err) {
  console.log(err);
});
```

Stack:

``` javascript
TypeError: Object #<Object> has no method 'getPrimaryUser'
    at Object.getPreferredSymAlgo (/myProject/node_modules/openpgp/src/key.js:1017:31)
    at Message.encrypt (/myProject/node_modules/openpgp/src/message.js:150:27)
    at /myProject/node_modules/openpgp/src/openpgp.js:96:15
    at /myProject/node_modules/openpgp/src/openpgp.js:290:18
    at invokeResolver (/myProject/node_modules/openpgp/node_modules/es6-promise/dist/commonjs/promise/promise.js:41:5)
    at new Promise (/myProject/node_modules/openpgp/node_modules/es6-promise/dist/commonjs/promise/promise.js:28:3)
    at execute (/myProject/node_modules/openpgp/src/openpgp.js:289:17)
    at Object.encryptMessage (/myProject/node_modules/openpgp/src/openpgp.js:93:10)
    at /myProject/test.js
```

The pubkey does seem to be properly imported:

```
{
  keys: [ { primaryKey: 
     { tag: 6,
       version: 4,
       created: Fri Mar 28 2014 15:44:03 GMT-0400 (EDT),
       mpi: [Object],
       algorithm: 'rsa_encrypt_sign',
       expirationTimeV3: 0,
       fingerprint: '38d12b6ebc695582f83bc9cfd8021933f751a0dd',
       keyid: [Object],
       packets: [Object] },
    revocationSignature: null,
    directSignatures: null,
    users: [ { userId: 
     { tag: 13,
       userid: 'Rob Riddle <rob@xxxxxx.com>',
       packets: [Object] },
    userAttribute: null,
    selfCertifications: [ [Object] ],
    otherCertifications: null,
    revocationCertifications: null } ],
    subKeys: [ [Object] ] } ]
}
```

Version: `openpgp@0.11.0`
OS: `OSX 10.9`
Node: `v0.10.26`

**Comment by Matze2010** [comment]
I seem to have the same issue. From what I can tell this is related to Safari browsers. The problem arrises on iOS Safari and Windows Safari. Did not test it on Mac Safari yet.

**Comment by taurit** [comment]
I ran into similar problem today and debugged it. In general, this error seem to occur when the first argument passed into *encryptMessage()* method is of invalid type. It should be *Key[]* which have *getPrimaryUser()* method defined via prototype in openpgp.js file (so that's not some browser-specific API missing).

It seems to be an easy mistake to make: when passing single key it's easy to forget pubkeyobject**.keys** part, and when passing array of keys it works as an **union** of those arrays, not array of arrays.

I can't see any mistake like this in the code posted, but it's worth to check twice whether *encryptMessage()* has this parameter right for those who run into this problem.

**Comment by michal-autin** [comment]
I know this bug is old, recently I encounter it on my own.

The reason was I passed unresolved promise as a public key option, not the key itself. It took me an hour to asses what was wrong because the error message wasn't clear about it. Can we adjust it to reflect the real problem - not a valid public key for encryption?

My error message was:
```
{
    "errorMessage": "Error encrypting message: key.getPrimaryUser is not a function",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Error encrypting message: key.getPrimaryUser is not a function",
        "    at \\fh\\node_modules\\openpgp\\dist\\openpgp.js:34319:35",
        "    at Array.map (<anonymous>)",
        "    at getPreferredAlgo (fh\\node_modules\\openpgp\\dist\\openpgp.js:34318:26)",
        "    at Message.encrypt (fh\\node_modules\\openpgp\\dist\\openpgp.js:35103:96)",
        "    at fh\\node_modules\\openpgp\\dist\\openpgp.js:36001:20",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}```

another environment, the same root cause:
```
TypeError: Error encrypting message: Cannot read property 'getPrimaryUser' of undefined
at /var/task/node_modules/openpgp/dist/openpgp.js:34319:35
at Array.map (<anonymous>)
at getPreferredAlgo (/var/task/node_modules/openpgp/dist/openpgp.js:34318:26)
at Message.encrypt (/var/task/node_modules/openpgp/dist/openpgp.js:35103:96)
at /var/task/node_modules/openpgp/dist/openpgp.js:36001:20
at <anonymous>
```

**Comment by michal-autin** [comment]
Error appears when using bugged doc snippet, mentioned (https://github.com/openpgpjs/openpgpjs/issues/932#issue-467593432)
