### ISSUE TITLE
Decryption/encryption progress tracking

### ISSUE THREAD

**Issue by let4be** [openpgpjs/openpgpjs#325]
Is there any way to track progress/eta on such operations as decryption/encryption and key generation?

I can currently think of splitting data into multiple pgp-envelopes do each operation would take smaller portion of time, is there a better way?

**Comment by alax** [comment]
Encryption should be instant in most environments, even mobile. Decryption takes 99% of it's time on these two lines:

https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/public_key/rsa.js#L81-L82

Since those are synchronous operations, unless it's entirely re-written, there is no way to get the status of an in-progress decryption. Splitting data into multiple envelopes would probably have the opposite effect that you want; it would increase most likely increase your decryption time linearly for each envelope.

**Comment by tanx** [comment]
Don't see how to implement this currently
