### ISSUE TITLE
Browser Dependency

### ISSUE THREAD

**Issue by dalerobbins** [openpgpjs/openpgpjs#338]
Has anyone thought to take a look at https://www.grc.com/otg/uheprng.htm for a high entropy random number generator so that the browser requirements can be relaxed?

**Comment by fxa** [comment]
Oh my God! The days of inventing new PRNGs in js is over. We have well
designed algos, well implemented and reviewed an pentested code and it
is all relevant browsers. Even chrome uses not only new Date() to seed
the PRNG on windows machines but uses CAPI since autumn 2013.

new js PRNGs (and yes, I wrote my own some years ago) are snakeoil!

just my 2 cents

fxa

**Comment by tanx** [comment]
ACK
