### ISSUE TITLE
Decrypting with a public key

### ISSUE THREAD

**Issue by brunobg** [openpgpjs/openpgpjs#346]
Is it possible to encrypt with a private key and decrypt with a public key? I want to send data that is guaranteed to be from a sender and I'd rather not send it as clearText, so just signClearMessage() is not an option. decryptAndVerifyMessage() requires both the public and private keys, so also not an option.

I can encrypt with a private key easily:

```
	var publicKey = openpgp.key.readArmored(fs.readFileSync('public.key', 'utf-8'));
	var privateKey = openpgp.key.readArmored(fs.readFileSync('private.key', 'utf-8')).keys[0];
	privateKey.decrypt(PASSPHRASE);
	openpgp.encryptMessage(privateKey, text).then(function(pgpMessage){ // yes, private });
```

But trying to decrypt with a public key does not work.  This returns `Error: Private key is not decrypted.`

```
	pgpMessage = openpgp.message.readArmored(pgpMessage);
	openpgp.decryptMessage(publicKey.keys[0], pgpMessage).then(function(plain) {
		....
	});
```

But `publicKey.keys[0].decrypt(PASSPHRASE)` throw `Error: Nothing to decrypt in a public key`.

Any tips?

**Comment by Gaff** [comment]
How exactly do you define "not send it as clearText"? Could you just sign the message and then base64 encode it?

**Comment by brunobg** [comment]
I'd rather send the encrypted data. base64 encoding adds no protection at all.

In theory there's nothing wrong with encrypting with the private key and decrypting with the public one, and since encryption already works, I wonder if decryption isn't working just because some if() is blocking it by accident.

**Comment by axelmartensson** [comment]
Hi!
It sounds to me that you are trying to sign a message, see https://en.wikipedia.org/wiki/Public-key_cryptography#Digital_Signatures for a definition.

there are functions for signing messages, for instance 
openpgp.signClearMessage(), see 
https://github.com/openpgpjs/openpgpjs/blob/291b9f2cd20affc8e33479975c6ffed18e4aba94/src/openpgp.js#L190

**Comment by Mithgol** [comment]
It sounds to me that @brunobg was trying to encrypt the message with a private key and decrypt with the corresponding public key. It has all the benefits of a digital signature (i.e. the message's origin is clearly the private's key owner) but the message's content also remains hidden unless the public key is correct and corresponds to the private key.

However, @brunobg also says “I'd rather not send it as clearText” but the message encrypted with a private key (and decryptable with the corresponding public key) is no better than clearText in terms of protection (because a public key is, well, public). The correct mode of operation here is, I guess, signing the message with the sender's private key **and then** encypting with the receiver's public key; that message upon arrival should be given to `decryptAndVerifyMessage()` which in turn correctly “requires both the public and private keys” (i.e. the sender's public key and the receiver's private key).

**Comment by brunobg** [comment]
@Mithgol is correct in his first paragraph. I understand that it does not add extra security, but the message is hidden and cannot be easily edited by users. (Why I want this? I'm trying to avoid users tampering with data that they should not change and break everything because they open files in text editors and mess them up).

I do not want to send both the private key and the public key to the client. This would defeat any sort of security and be worse than just signing the message.

**Comment by Mithgol** [comment]
> I do not want to send both the private key and the public key to the client.

By the way, where exactly do you get the impression that both of them would be necessary?

**Comment by Bene81** [comment]
I believe it is just a misunderstanding. As far as I can tell, all of you are right. No need to justify either one way or the other.

The point is, brunobg wants to encrypt data with his private key which is somewhat similar to signing but has some advantages in certain scenarios. I could instantly think of trivial licensing without some "superclever" noobs trying to extend their license by modifying that file and therefore voiding their license file creating a support case. To avoid that, don't sign, encrypt and embed public key in application. Of course there are better ways of licensing, I am not discussing that, it is just a legitimate use case someone could consider. Low cost, highly effective.
I am sure there are plenty of others scenarios someone could use encryption with private key instead of signing. The main purpose is:

- obfuscate data to normal users that mess with data but have no idea (what they are doing)
- ensure data is provided by certain person and therefore valid (authenticate/data integrity)

The absolute amazing thing with openPGP is, that you can use it for so many applications, not only for encryption and authentication, but for anything where enryption and authentication are the mere tools an vehicles. Something that fits perfectly into the bigger picture.

**Comment by brunobg** [comment]
@Mithgol I'd need to send both if I used `signAndEncryptMessage` and `decryptAndVerifyMessage`, with a single set of keys (which is not how it is supposed to be used, of course). 
@Bene81 exactly, I agree 100%. 

Back to the issue itself: as I mentioned, encrypting with a private key already works, but decrypting with a public key doesn't. Would it be an easy fix?

And thanks to everyone who is pitching in :)

**Comment by tomaspinho** [comment]
I also need the same functionality (encrypting with private, decrypting with public). So I guess I'll have to resort to some other library or cli exec :(

**Comment by bartbutler** [comment]
I'm also mystified as to why this is necessary. Signing the message means you are protecting against editing by others, assuming the receiver is checking the signature. This really adds nothing except confusion, unless I'm missing something.

Also, I could be wrong about this but 'encrypt with private key working' sounds strange to me too. The reason is that the private key INCLUDES a copy of the public key--my guess is that 'encrypting with private key' is actually encrypting with the public key anyway.
