### ISSUE TITLE
Evaluate removal of the Promise polyfill and eventually other polyfill requirements and delegate inclusion  of them to the user

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#370]
I've found out that in various libraries we use on GlobaLeaks the inclusion of polyfills is delgated to the user.

I'm not sure about the best practice but i find this a good practice but i'm  now considering that this should be done also by openpgp.js

Let me clarify with an example.

Suppose a user want to:
1. include an  important library in the first startup of the app to do important checks before the app  starts and so before openpgp.js will be loaded; and suppose that library requires Promises polyfill.
2. include openpgp.js  that currently embeds the polyfill for Promises.

by current design of openpgp.js that includes a Promise polyfil, to do  1),  the user will be forced to include the  promise polyfill twice, one in 1)  and one second time in two  by loading openpgp.js.

**Comment by toberndo** [comment]
Sounds good to me. We can document the dependencies and link to recommended shims.

**Comment by bartbutler** [comment]
What about the Web worker? It probably needs to keep the shim. I'm fine
with having it separate for the main thread though.

**Comment by toberndo** [comment]
@bartbutler There is currently no shim included in the build for web worker. Only a mechanism to use your own Worker object here: https://github.com/openpgpjs/openpgpjs/blob/master/src/worker/async_proxy.js#L42

**Comment by tanx** [comment]
@bartbutler is right. You would need to include a Promise polyfill in the main window context as well as the Web Worker context (at least to support older browsers). That's why I included the es6-promise polyfill directly in the openpgp.js build, as both contexts just load that single scipt file.

I have had trouble with the polyfill in the past though. So removing it might male things easier in certain scenarios. But it would denititely make it harder to get started with OpenPGP.js for newcomers. Since they would have to figure out how to get openpgp.js, openpgp-worker.js, and Promises wired up. My hope was to shield users of the library from this complexity.

**Comment by toberndo** [comment]
@tanx got it. If the user requires to patch openpgp.worker.js to load the Promises polyfill then that adds complexity. If we keep the polyfill in the worker then removing it from the main context looks inconsistent to me.

**Comment by evilaliv3** [comment]
i see @tanx; i agree that we should not raise the complexity so for sure we need it in the webworker and let's keep it.

for what relates to the openpgp.js one possibility is to provide it in two version, one with polyfills that is something done by other libraries.

and probably we can simplyf the new comers and the legacy user that will simply update by calling:
- openpgp.js (the one with polyfills in)
- openpgp-no-polyfills.js (the one without polyfills in)

what do you think?

**Comment by tanx** [comment]
Don't really see the need for that extra conplexity in the build process given that promises is our only packaged polyfill. Once IE11 marketshare is low enough we can remove it anyway. Until then if a user wants a smaller build, it's quite straitfroward to remove the polyfil via code comment.
