### ISSUE TITLE
API parameter missmatches

### ISSUE THREAD

**Issue by henryboldi** [openpgpjs/openpgpjs#411]
password or passphrase? data or message?

**Comment by tanx** [comment]
Sentences? You can do it.

**Comment by henryboldi** [comment]
My apologies, I'll try to use sentences in the future. Thanks for the great work Tankred!

It's not initially clear to me the distinction between message vs. data, and passphrase vs. password. Hopefully, this issue can serve as an explanation to others.

#### Passphrase vs. Password
A `passphrase` is used with private keys, whereas `password` is for dealing with messages.

#### Message vs. Data
A `message` is a particular object (see: [docs for module message](http://openpgpjs.org/openpgpjs/doc/module-message.html)) and is used when decrypting or verifying. On the other hand, `data` is unspecific and used when encrypting or signing. `data` is utilized in those instances since they're absent from any metadata that would be in a message object like signatures.

**Comment by tanx** [comment]
Yeah. That's basically it. `data` is an arbitrary payload either as String or a Uint8Array. Where as message is actually of type `Message`.

The main reason for the different names is just that some types need to be cloned to a packet list before being passed to the web worker. Otherwise the browser's structured cloning algorithm doesn't work. We could just detect types, but using different parameter names for different types also makes the api more descriptive.

Your comment about passphrase and password is entirely correct. I think I tried to use similar vocabulary as GnuPG where I could here.
