### ISSUE TITLE
Introduce a general support for time-padding to prevent side-channel JS-crypto usual critics

### ISSUE THREAD

**Issue by fpietrosanti** [openpgpjs/openpgpjs#422]
This ticket is to Introduce a general support for time-padding to prevent side-channel JS-crypto usual critics.

Any kind of side-channel / timing-based attacks to cryptography can be roughly fixed with the dirty approach of "time-padding", that prevent an attackers from having accurate timing-information on crypto operations.

This ticket is to introduce, by default enabled, a time-padding feature to mitigate side-channel attacks to almost any kind of JS-crypto.

The time-padding security feature must be implemented with a real-world approach, meaning that it must be effective to defeat most side-channel attacks (maybe not all), but shall not impact real-life operations of end-user applications (e.g.: a time padding of randomized 20-30 seconds would provide surely an impact, but a time padding of a random interval between 150-450, would not likely impact any end-users operations).

**Comment by tanx** [comment]
My 2 cents...

1. This will probably reduce performance quite a bit and performance >> timing attack vector.
2. If we move towards native crypto apis, the issue is resolved in the longterm anyway
3. Given that we barely have enough resources/time to do asm.js optimzations, I don't see anyone stepping up to pay/do the work required for this.
