### ISSUE TITLE
Move localstorage keyring to its own module

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#425]
As part of an effort to make the core library leaner and meaner we should create a new git-repo/npm-module named `openpgp-keyring` that can be used optionally by users of OpenPGP.js.

This would also remove `node-localstorage` as a direct dependency of OpenPGP.js.

**Comment by mapmeld** [comment]
I did an initial test to see how this might look: https://github.com/mapmeld/openpgp-keyring

Bundling issues:
- the keyring needs a Key object, which should be shared with OpenPGP.  Can we avoid bundling so much of OpenPGP with this module?

ES6 issues (couldn't get ES6 versions working on my machine)

- In src/keyring/keyring.js and src/keyring/localstorage.js there should be the line ```import key as keyModule from 'openpgp'``` replacing ```var keyModule = require('openpgp').key;```
- I wrote ```Keyring = require('../dist/openpgp-keyring').default;``` in the test because ES6 ```import '../dist/openpgp-keyring'``` did not work in my mocha setup

**Comment by twiss** [comment]
Removed in 4a8fffdfdf94ca88f3624db6c7572611d1404eaf. Keyring handling and storage should be handled in the application, as localStorage may not meet the durability requirements of the application, for example.
