### ISSUE TITLE
Implement ECC support for Curve Ed25519 (IETF draft)

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#428]
See https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-00

This issue tracks the implementation of EdDSA for Curve Ed25519. Unlike the NIST curves, the IETF has not standardized this as an RFC. Also, there is no native support in the WebCrypto api yet. In spite of this [GnuPG v2.1 uses Curve25519 as the default](https://www.gnupg.org/faq/whats-new-in-2.1.html#ecc). So we should add support to stay compatible and could use a JS implementation until native support exists in both WebCrypto and node.js.

Available JS implementations:
https://github.com/joebandenburg/libaxolotl-crypto-curve25519
https://github.com/indutny/elliptic
https://github.com/google/end-to-end/tree/master/src/javascript/crypto/e2e/ecc

**Comment by tanx** [comment]
elliptic seems to be the most popular implementation, looks well tested, and it's being actively maintained by @indutny:

https://github.com/indutny/elliptic

Regarding performance, there are some [benchmarks](https://github.com/indutny/elliptic/blob/master/README.md#benchmarks). Although it does not seem to use typed arrays, where as this asm.js compiled library does:

https://github.com/joebandenburg/libaxolotl-crypto-curve25519

In any case good quality code, tests, and active maintenance are probably more important.

**Comment by rmhrisk** [comment]
On browser can use WebCrypto, I made a server side WebCrypto also, it is done in TypeScript which compiles down to ES5 with Babel - https://github.com/PeculiarVentures/node-webcrypto-ossl

**Comment by tanx** [comment]
Unfortunately we can use WebCrypto only for NIST curves right now. See https://github.com/openpgpjs/openpgpjs/issues/427.

I like the idea of using a single api for node and the browser, but as mentioned on Twitter I'd prefer to use a wrapper for the node crypto api than a custom OpenSSL build. Node.js has a huge community relying on it's release process with timely security updates.

**Comment by indutny** [comment]
As a maintainer of elliptic, I would like to say thank you guys for considering it. Please let me know if I could be any help to you.

**Comment by rmhrisk** [comment]
it is not a custom OpenSSL build it is a binding to openssl. That said I understand the desire to use something with a staffed security process around it.

**Comment by rmhrisk** [comment]
If you wanted to do a JS polyfill for webcrypto based on @indutny's great work I would base it on - https://github.com/vibornoff/webcrypto-shim

**Comment by tanx** [comment]
@indutny thanks! Willlet you know if we have some questions.

@rmhrisk good idea. We could do a very simple WebCrypto shim specifically for our needs that:

1. wraps our required crypto primitives AES-GCM, Curve P-* which are alreay supported natively by the node crypto modul
2. wraps @indutny's eleptic code as a JS fallback in case there is no native support yet e.g. for Curve25519.

**Comment by rmhrisk** [comment]
Another you might look at is : http://research.microsoft.com/en-us/downloads/29f9385d-da4c-479a-b2ea-2a7bb335d727/

**Comment by evilaliv3** [comment]
i support the idea of integrating Webcrypto+elliptic! nice @rmhrisk !

@indutny have you experimented if if can switch to use internally TypedArrays and if the library would be more efficient?

**Comment by indutny** [comment]
@evilaliv3 yes, I experimented with this, and it turned out to be slower in the case of elliptic.

**Comment by evilaliv3** [comment]
@tanx i've started reviewing the indutny/elliptic library and to do it more efficiently i've implemented all the quality measure that we have in place on openpgp.js.

This way if we go for that we know that the library is really functioning on all the browsers we target.

**Comment by evilaliv3** [comment]
@rmhrisk: I'm not that certaint that webcrypto-shim would be helpful in the end, given the fact that it's really a new project and i do not thing that much developed but let's see if we can share some forces.

**Comment by rmhrisk** [comment]
@evilaliv3 agreed, in part this is why I made https://github.com/PeculiarVentures/node-webcrypto-ossl and https://github.com/PeculiarVentures/node-webcrypto-p11. In my projects, I am trying to maintain a singular API for crypto operations across server and client and instead of coming up with my own or shoehorning into someone else I decided to settle on WebCrypto.

I have been using the webcrypto-shim to deal with a Safari limitation that exists in their WebCrypto implementation and have had good experience with the code base. That said I explicitly have decided to not use JS crypto so I have not looked at the code in this part of the project.

I share it here only so you know it is something you might be able to build upon given the above context in this bug.

**Comment by tanx** [comment]
May I suggest that we start ECC support with https://github.com/openpgpjs/openpgpjs/issues/427. The P curves are after all available natively. That together with AES-GCM https://github.com/openpgpjs/openpgpjs/issues/421 will give us an all native symmetric+asymmetric cipher suite. GCM may not be widely supported by other OpenPGP implementation yet so interoperability will initially be a problem, but for projects that are not reliant on interop and just encrypt within their application, this woule be a massive step in terms of performance and security.

**Comment by evilaliv3** [comment]
we were discussing with @fpietrosanti exactly the same; in general also when not explicitly needed the library should prefer the ciphers that are available in webcrypto, and use the others in compatibility for decryption. good to go for that first step

**Comment by tanx** [comment]
Agreed. GCM is currently used by default in my initial impementation. See: https://github.com/openpgpjs/openpgpjs/pull/430

Users can turn that off by setting `openpgp.config.aead_protect = false` which will then use integrity protected packets with asm.js implementations of CFB+SHA-1.

**Comment by evilaliv3** [comment]
By the way the good way to go for this is to use: https://github.com/bitchan/eccrypto

eccrypto provides different implementations for Browser and Node.js with the same API. Because WebCryptoAPI defines asynchronous promise-driven API, implementation for Node needs to use promises too.

- Use Node.js crypto module/library bindings where possible
- Use WebCryptoAPI where possible
- Promise-driven API
- Only secp256k1 curve, only SHA-512 (KDF), HMAC-SHA-256 (HMAC) and AES-256-CBC for ECIES

internally it uses ellliptic.js library for the fallback on javascript implementation.

**Comment by rmhrisk** [comment]
Node has promises now also.

**Comment by pzduniak** [comment]
Starting a new project it feels that it would be easier to introduce x25519 support to kbpgp and add all required features into that library rather than modifying OpenPGP.js.

Has there been any progres on this front or is most development done by Proton, who clearly don't care about improving their product (and instead focus on user acquisition).

**Comment by bartbutler** [comment]
@pzduniak ECC support would be great, and you are welcome to create a pull request. I do not think your attacks on ProtonMail are either fair or appropriate for this setting.

**Comment by pzduniak** [comment]
I read somewhere that the library was pretty much designed to only support RSA and other RFC4880 so it's difficult to implement additional features, since it would require rebuilding of various parts of the app. If this is true, then naturally I am going to go with the lowest effort solution, which now seems to be using kbgpp and implementing x2559 there (they already have support for NIST curves).

Proton, as the company, clearly doesn't care about implementing new features / pushing OpenPGP forward (it's not like you support sending OpenPGP emails either) so it's not like I am expecting anything to be done by the company. I hold no grudges against any single person in the company (maybe except the guy who runs the Reddit account, people must love when he attacks them).

**Comment by andreis** [comment]
👍  for wanting ECC support

My friend @pzduniak is a bit OTT but his heart is in the right place. Supporting open standards helps everyone in this market, users and companies.

**Comment by bartbutler** [comment]
@andreis, I completely agree re: open standards, and now that I have figured out why your names are familiar to me, his attitude is somewhat understandable if still not appropriate.

In terms of the suitability of OpenPGPjs for expansion to support elliptic curves, nothing in my experience with the library would imply that it would be overly difficult to implement, and the existence of a PR that implements some curves already (see https://github.com/openpgpjs/openpgpjs/pull/484) would imply the same. That said, it may very well be easier to work on the existing ECC support in kbpgp. I do expect to devote more time to ECC soon as ProtonMail edges closer to full external PGP support.

**Comment by evilaliv3** [comment]
as GlobaLeaks we are also interested and we are able to put work time on this in the next months.

our interest is mostly in supporting the integration of the curves present in the webcrypto API.

@bartbutler / @pzduniak maybe we can all join the effort and make it?

**Comment by tanx** [comment]
If I may chime in...

> I read somewhere that the library was pretty much designed to only support RSA and other RFC4880 algos so it's difficult to implement additional algorithms, since it would require rebuilding of various parts of the lib.

While it's true that some parts of the architecture rely on public key encryption being BigNum/RSA based, there is nothing standing in the way of adding a layer of abstraction on top of this to ease ECC integration. We have certainly improved the modularity of the library over the years, OpenPGP.js v2.x being a big step in that direction (ProtonMail having funded me for a large part of that work).

In regards to the criticism towards ProtonMail, I obviously cannot speak on their behalt, but @andreis and @pzduniak can certainly empathize with the difficult market situation for monetizing encrypted email. Unfortunately markets reward closed messaging ecosystems rather than open standards. [Moxie's post on federation](https://whispersystems.org/blog/the-ecosystem-is-moving/) talks in depth about this dynamic, which is why I have become careful nowadays with criticizing companies or products. I felt that is was the best decision to let ProtonMail continue the maintenance of OpenPGP.js precisely because they have been able to grow a sizeable user base and are basically the only startup that has survived the post-Snowden encrypted email startup hype (@whiteout-io being among the many failed attempts).

Having said that I would certainly welcome PGP interop in ProtonMail. It is the only missing feature for me personally that would convince me to switch from Gmail ;)

**Comment by bartbutler** [comment]
Thanks @tanx, I completely agree, including that part that the lack of interoperability is a glaring problem with ProtonMail at the moment. You have no idea how desperately I want to fix this :)

**Comment by wswoodruff** [comment]
Any updates on this?

**Comment by bartbutler** [comment]
It is being actively developed, stay tuned!

**Comment by HLFH** [comment]
@bartbutler Any news?

**Comment by bartbutler** [comment]
It's a little bit in development purgatory due to staffing, but we are hoping to get it done in Dec 17 or Jan 18 latest. It's mostly done except certain things need to be 'webcrypto-ified' to be faster.

**Comment by HLFH** [comment]
@bartbutler @sanjanarajan Hi. Can we close this issue since https://github.com/openpgpjs/openpgpjs/pull/618 has been merged?

**Comment by bartbutler** [comment]
Not yet, it was merged into the main ecc_nist branch--we'll close it when it gets merged into the master.

**Comment by mahrud** [comment]
Happy to close :D
