### ISSUE TITLE
openpgp overrides Promise in node environment

### ISSUE THREAD

**Issue by SimonSchick** [openpgpjs/openpgpjs#455]
Version: 2.3.0
Node: 4.4.2
Description:
We are using opengpg and I tried to update to the newest version, by doing that our whole integration tests started to fail due to timeouts, I'm still not entirely sure where they time out, due to the complexity of our system, but it's probably in one of our dependencies.

After inspecting the global object and eventually applying `Object.freeze(global)` I figured out openpgp is is apparently overriding/polyfilling promises in a node environment that doesn't require it.
Somewhere in the implementation there seems to be a problem, eventually causing an event loop starvation.

Can you perhaps looking into not polyfilling Promises in node environments that already implement them?

**Comment by tanx** [comment]
Can you please test if the following branch resolves the problem:

https://github.com/openpgpjs/openpgpjs/pull/456

Just git clone and do `npm install && grunt` to build openpgp.js. The just copy the files from `dist/` to your node_modules/openpgpjs/dist/ directory.

**Comment by SimonSchick** [comment]
It's still polyfilling it with your changes.

**Comment by tanx** [comment]
Ok. Thanks for checking. It's probably because our browserify/babel build includes the polyfill and the environment detection is broken under node due to browserify.

@evilaliv3 suggested to leave out polyfills out of the build completely. I guess we will have to go this route even though it will make it harder to use th library on older browsers. Devs will need to include the polyfill in both the main window as well as in the web worker context.

**Comment by bartbutler** [comment]
I feel like leaving out the polyfill is fine for the main window but is going to cause major usability issues for the web worker. I suggest we either figure out why the environment detection is broken (it used to work---we have an older OpenPGP.js build in production with node 0.12 with no issues) or remove the polyfill for the main context only--the the web worker should never been used under node anyway. I'm not certain the web worker _can_ be used under node.

**Comment by tanx** [comment]
@bart which version of OpenPGP.js are you using in production?

I remember also having trouble in my travis build for the new Promise polyfill with PhantomJS v1.x. This is why I kept the version `^1.0.0` of the polyfill for such a long time. That version is ancient but got the job done.

I bumped the es6-promise dependency recently because PhantomJS v2.x could handle the new version. I could revert that change.

**Comment by bartbutler** [comment]
For node we are still using our fork of 1.2.0, basically the v2.0 pull request before you cleaned it up.

**Comment by tanx** [comment]
Well that has version `^1.0.0` for sure. I'm surprised the OpenPGP.js travis build isn't failing. We run the mocha tests in browsers via saucelabs as well as under node 0.12.x, 4.x and 5.x 🤔

**Comment by tanx** [comment]
So I've figured out what the problem is. See: https://github.com/stefanpenner/es6-promise/issues/140

I don't agree with their solution to override V8's native implementation "because it is buggy" if their polyfill is causing our users' builds to fail. Their proposed solution is to patch V8, which is fine, but doesn't solve our issue. In the meantime I have created a fork: https://github.com/openpgpjs/es6-promise/compare/master...openpgpjs:fix-node-detection-dist

@SimonSchick could you please verify that this fixes your build issues. Thanks: https://github.com/openpgpjs/openpgpjs/pull/457

**Comment by tanx** [comment]
I assume the issue is resolved and there is no longer need for the patch.
