### ISSUE TITLE
Error: Error encrypting message: Could not find valid key packet for encryption in key

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#468]
I have a key that has a subkey for encryption, but openpgp.js cannot find it, also gpg v1 seems not able to deal with it.

As soon as I import it in gpg2 it works. Also when I export it from gpg2 back into openpgp.js it works.

The only thing different I can see, the user used a mac version of gnupg and the user added the same user id on different dates.

[key.asc.zip](https://github.com/openpgpjs/openpgpjs/files/307326/key.asc.zip)

OpenPGP.js tries to find the encryption subkey in the public key, and as a result fails to encrypt with this key throwing:
openpgp.js:15591 Uncaught (in promise) Error: Error encrypting message: Could not find valid key packet for encryption in key 06e101c1be67b669
    at onError (file:///home/bar/Desktop/scripts/openpgp.js:15591:9)

[encrypt-test1.html.zip](https://github.com/openpgpjs/openpgpjs/files/307336/encrypt-test1.html.zip)

In case no one picks up this issue, it is here for reference.

**Comment by kellerben** [comment]
I got the same error message with this key:
http://pgp.mit.edu/pks/lookup?op=vindex&search=0x3AE93DF24F980AB6

**Comment by jmesserli** [comment]
I have the same error with the key described in whitesmith/hawkpost#185. 

([https://pgp.mit.edu/pks/lookup?op=get&fingerprint=on&search=0xF3140E4A8D56FF55792112EF3F77CE4377661AF7](https://pgp.mit.edu/pks/lookup?op=get&fingerprint=on&search=0xF3140E4A8D56FF55792112EF3F77CE4377661AF7))

**Comment by sanjanarajan** [comment]
@barrydegraaff - it looks like your subkey is being correctly found, but it is no longer valid for encryption because it expired on Thu Apr  7 15:00:00 PDT 2016

@kellerben - your subkey does have a valid signature packet (expiring Fri Jul 14 04:09:52 PDT 2017) but it is followed by an invalid signature packet (expiring Mon Dec 10 14:25:41 PST 2012). Currently, the last signature packet is used to validate the key, but in the future we may support using any valid signature packet to validate the key.

**Comment by kellerben** [comment]
This still is a bug and you should not close it but either handle it as a feature request (to support more than one signature at a key) or adopt the error message to a more useful one (to avoid people opening a similar ticket).
or do both…

**Comment by bartbutler** [comment]
I don't believe it is a bug--I think from following the RFC one would conclude that the key is corrupt. That said, I'll reopen and tag as a feature request.

**Comment by barrydegraaff** [comment]
This must have been a bug in gnupg2 then, this morning I re-imported the above key, before gnupg2 lists:

pub   rsa4096 2014-04-07 [SC] [expires: 2021-04-07]
      BEBC99CC550EEE4F2E91813B06E101C1BE67B669
uid           [ unknown] Ali Ravi <a.ravi@riseup.net>
sub   rsa4096 2014-04-07 [E] [expires: 2021-04-07]

remove the key from keyring and re-import:

pub   rsa4096 2014-04-07 [SC] [expired: 2016-04-07]
      BEBC99CC550EEE4F2E91813B06E101C1BE67B669
uid           [ expired] Ali Ravi <a.ravi@riseup.net>

Funny how that works :-p don't know if gnupg2 has a changelog somewhere, but I am noticing more issues with gnupg2. Anyway this key does not have other signatures, so in this case a nicer error message would be great.

**Comment by barrydegraaff** [comment]
@sanjanarajan I wonder if openpgp.js allows encrypting to expired keys or not, for example this one:
[a.asc.zip](https://github.com/openpgpjs/openpgpjs/files/555142/a.asc.zip)

I can use it for encryption in openpgp.js, but it is expired:
pub   rsa2048 2012-07-22 [SCEA] [expired: 2016-07-22]
      4E777AF9EFD91EFFBEBCE625CC44A3EEC7873A47
uid           [ expired] Tane Lee Fang Fang <Leetane@gmail.com>


Again, it does seem to work when used for encryption, so maybe your above comment is not the cause for the problem with the a.ravi key.

**Comment by barrydegraaff** [comment]
@sanjanarajan @bartbutler 

As I look at this page:
https://sks-keyservers.net/pks/lookup?op=vindex&search=Ali+Ravi+%3Ca.ravi%40riseup.net%3E

      pub  4096R/BE67B669 2014-04-07            
      uid Ali Ravi <a.ravi@riseup.net>
      sig  sig3  BE67B669 2014-04-07 __________ 2016-04-07 [selfsig]
      sig  sig3  BE67B669 2016-04-08 __________ 2021-04-07 [selfsig]
      sub  4096R/AB9E865D 2014-04-07            
      sig sbind  BE67B669 2014-04-07 __________ 2016-04-07 []
      sig sbind  BE67B669 2016-04-08 __________ 2021-04-07 []

I can understand what happened here, user created a key with a validity of 2 years, but still wanted to use it after 2 years, so added another self-signature for a period of 5 years, till 2021.

So that one still does not work with openpgp.js and also does not work with gnupg2... I wonder if it is allowed to re-use an expired key like this.

**Comment by sanjanarajan** [comment]
@barrydegraaff - good point, actually the leetane@gmail.com key should also have been considered invalid due to expiration. 

When encrypting with a public key, we first try to encrypt with a valid subkey. If all subkeys are invalid (expired, for instance), then the primary key is used for encryption. However, we were not previously checking the primary key's expiration (this is fixed by #494), so expired public keys could be successfully used for encryption.

The reason for the inconsistency between the a.ravi and leetane keys is that a.ravi's primary key only has the key flags set for certifying other keys and signing data (see 5.2.3.21 in RFC 4880). The leetane primary key, however, additionally has the flags set for encrypting communications and storage. Thus, before #494, a.ravi's primary key was invalid for encryption while leetane's was not.

**Comment by barrydegraaff** [comment]
@sanjanarajan thank you very much for your explanation, I understand now. @bartbutler and @sanjanarajan thanks a lot for fixing it in #494.
