### ISSUE TITLE
Can I use openpgpjs in a browserified application

### ISSUE THREAD

**Issue by iamolivinius** [openpgpjs/openpgpjs#472]
I've tried it the naive way, created an `main.js` file

    var openpgp = require('openpgp')

and run the browserify-cli on it

    browserify main.js

Unfortunately it exits with a error:

    Error: Cannot find module './config' from '/home/USER1/Documents/test/node_modules/openpgp/dist'
        at /home/USER1/.npm-packages/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
        at load (/home/USER1/.npm-packages/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
        at onex (/home/USER1/.npm-packages/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
        at /home/USER1/.npm-packages/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
        at FSReqWrap.oncomplete (fs.js:117:15)

**Comment by wgromniak** [comment]
I have the same problem, installed via npm, requiring with ES6 import syntax.

Other mentions: #438, [this SOF question](http://stackoverflow.com/questions/36819860/browserify-chokes-when-requiring-openpgp).

**Comment by fabrixxm** [comment]
Same here

**Comment by acasajus** [comment]
Same here. I'm using gulp:

```
Error: Cannot find module './config' from '/Users/acasajus/Devel/proj/front/node_modules/openpgp/dist'
    at /Users/acasajus/Devel/proj/front/node_modules/resolve/lib/async.js:55:21
    at load (/Users/acasajus/proj/front/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/acasajus/proj/front/node_modules/resolve/lib/async.js:92:31)
    at /Users/acasajus/proj/front/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by smcatala** [comment]
same error with https://wzrd.in: https://wzrd.in/standalone/openpgp@latest

**Comment by smcatala** [comment]
works fine with the following entry in `package.json`:

**Comment by iamdey** [comment]
And with an import ?

eg.

```
import openpgp, * as module from 'openpgp';
```

_(btw, I use webpack, works fine)_

**Comment by Ceany** [comment]
@smcatala your solution works fine. Thanks.

**Comment by fabrixxm** [comment]
worked with @smcatala solution

**Comment by iamolivinius** [comment]
Switched to kbpgp. Much cleaner API.

**Comment by acasajus** [comment]
To add some context. I have my own webworker in which I need to use openpgp. I've managed to use openpgp by manually concatenating a js header file, the openpgpjs dist file and then my js file and disabling it from browserify in my gulp file by hand.

In order to use openpgp in my webworker I've got to add to the header js file (that gets concatenated BEFORE openpgpjs file in my final webworker js file):

```javascript
//HACK for openpgp in a web worker
 var window = self;
 delete FileReaderSync;
```

- First one is to "trick" openpgp into using self instead of window to access ```self.crypto``` through ```window.crypto```. 
- The second is to disable the openpgp's webworker callback. 

It's a bit of a mess.

 I'm seriously considering switching to kbpgp also becase of the api. I haven't found a way generate a detached signature. I'm going crazy.

**Comment by bartbutler** [comment]
Thanks @iamolivinius for the PR. Left one comment, take care of that and I'll merge it.

@acasajus, running openpgp inside a web worker is tricky because it needs access to a secure random number generator, which is not available in the worker context for some reason. I'm not certain what 'self' is in your example--you really don't want to fake the random numbers. OpenPGPjs actually funnels secure random numbers from the mail window context.

I'd take a look at the openpgp worker.js and duplicate what it does if you need openpgp running inside a web worker, as it does exactly that:

https://github.com/openpgpjs/openpgpjs/blob/master/src/worker/worker.js

**Comment by acasajus** [comment]
@bartbutler Why can't you access the secure rando generator in the webworker? The MDN states that you can access the crypto global object through ```self.crypto``` at   https://developer.mozilla.org/en-US/docs/Web/API/Window/self .  In a webworker this works nicely:

```javascript
var array = new Uint32Array(10);
self.crypto.getRandomValues(array);
console.log( "Random data", array );
```

In any case I don't understand how you manage to prevent the ```self.onmessage``` callback in the FileReaderSync in the webworker code openpgp has. Can you give me some pointers on how to look that up?

Cheers,

**Comment by evilaliv3** [comment]
i agree with @acasajus;

self.crypto give access to the webcrypto API.
as far that i know the only browser not supporting this is Edge: let's blame this to microsoft https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13904769-support-web-crypto-api-inside-a-web-worker

(for the moment we could accept have a special bahaviour for edge only)

**Comment by acasajus** [comment]
@bartbutler thanks! 🍻

**Comment by acasajus** [comment]
@bartbutler Could you please give me a tip on how to disable the self.onmessage of the FileSyncReader? I don't see how it's done and it messes up my webworker if I don't delete it explicitly.

**Comment by bartbutler** [comment]
@acasajus, so the self.onmessage callback you are referring to is actually part of Rusha, the SHA1 library we use:

https://github.com/srijs/rusha/blob/master/rusha.js#L402

We overwrite this callback when we run OpenPGPjs in a webworker, as seen inside worker.js:

https://github.com/openpgpjs/openpgpjs/blob/master/src/worker/worker.js#L34

Can you not do this as well? Then you would not have to delete FileReaderSync. I agree that automatically setting self.onmessage is a little presumptuous, and maybe you can ask the author of Rusha to make it configurable, but I'm not sure why it is causing you problems.

**Comment by danielkerwin** [comment]
@bartbutler I've got a ~35mb (compressed) encrypted file that I'm struggling to decrypt because it locks up the browser - it takes about 3 minutes to decrypt during which time the browser is frozen.

When using the initworker function, the decryption never finishes - chrome seems to eventually run out of memory like there's a leak and the browser freezes.

I want to just run openpgp.min.js in a chrome web-worker, as I've had more success using this method, however am also plagued by missing modules (like 'stream').

Any suggestions on this old issue?
