### ISSUE TITLE
New maintainer wanted for OpenPGP.js

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#480]
Hey everyone,

I've decided it's time for me to move on from email/pgp to something new. It's been a lot of fun exploring what's possible in the protocol layer as well as in the user interface for encrypted email. But I haven't really found the time to respond to issues and PRs in this repo lately.

If anyone would like to fill in for the project, I would happily hand over the npm handle, domain and github ownership. Plus I'm still around and will happily assist in questions about the release process or any other way I can for the new maintainer.

A big thanks to the OpenPGP.js community. Even though it's very small, I'm very proud of the open and friendly tone in this project (which is sadly not the default for many security/crypto projects).

Tankred

**Comment by bartbutler** [comment]
This makes me very sad. You've been a great leader for the project @tanx. Good luck with your future endeavors, and let me know what I can do.

**Comment by bartbutler** [comment]
On that note, I volunteer on ProtonMail's behalf to be the new maintainer. We are very dependent on this project for our web app and would ensure it gets the support it needs.

**Comment by tanx** [comment]
> This makes me very sad. You've been a great leader for the project @tanx. Good luck with your future endeavors, and let me know what I can do.

Thanks Bart! No reason to be sad :) There is too much cool stuff going on in tech right now and after four years of email it's time to learn something new.

> On that note, I volunteer on ProtonMail's behalf to be the new maintainer. We are very dependent on this project for our web app and would ensure it gets the support it needs.

It makes sense for ProtonMail to step in, given it's one the most relevant users of the library next to Mailvelope. So no objections from my side. @toberndo and me are currently npm/github owners and can keep it that way to keep the truck factor high. Just send me your npm user via mail and I'll make the necessary changes.

**Comment by tanx** [comment]
Ok @bartbutler is now npm and github owner. I'm also transferring the openpgpjs.org domain and twitter handle to ProtonMail.

If you have any questions regarding release etc. just let me know. The two shell scripts `res/update_deps.sh` and `res/release.sh` should be pretty self explanatory.

Thanks for stepping up Bart! No doubt in my mind that the project is in good hands :)

**Comment by evilaliv3** [comment]
okay! i agree that @bartbutler could take the lead as it is important that one!

it will be really important that you @tanx facilitate us all in this migration as a lot of knowledge is in your great head; and thanks for your work done so far, and i'm sorry for your decision but i totally understand.

from my point of view anyhow for the maintenance and growth of the project it will be important to compose a team among the various stakeholder around the project.

protonmail, mailvelope, globaleaks are some of the relevant projects that are strongly coupled on openpgp.js and share the mission of openpgpjs and it will be important that we share the effort defining milestones for the project in order that it could accommodate all our needs;
in fact if we share a lot from one one hand, on the other each of us have its peculiarities and is interested in see specific aspects be improved in the library.

we should try to collaborate more in what are the priorities and guidelines for the next, so that the project could move forward easily, with good review and with every user satisfied

as we from globaleaks are tightly coupled to openpgp.js i confirm my availability in helping.

**Comment by tanx** [comment]
Agreed. An open source project is a meritocracy, and anyone who contributes obviously gets a say in technical decisions. This project has always been a team effort and I doubt ProtonMail has an interest in carrying the burden alone. Having said that, it's important to name a project lead who wears the hat as maintainer for releases and final decisions. If you guys want to decide who that person in a more transparent gonernance model by voting, that makes sense too. But from what I gathered from talking with @toberndo and your comments here, everyone kind of already agrees @bartbutler is an obvious choice.

**Comment by bartbutler** [comment]
Yes, this will of course continue to be a collaborative effort among all the stakeholders in the project. I think in general we are well-aligned with where we will need the project to go in the future (streaming, performance improvements, etc.).

**Comment by barrydegraaff** [comment]
@tanx a bit late in my reply, but I still want to thank you very much for all your effort on OpenPGP.js and wish you all the best with your future endeavors. Barry
