### ISSUE TITLE
Error decrypting message: Random number buffer depleted

### ISSUE THREAD

**Issue by eboily** [openpgpjs/openpgpjs#546]
Hi,

I am trying to speed up openpgp.js (latest commit dc04af4) using web workers and the native AES-GCM (adding the setup `openpgp.config.aead_protect=true`), as mentioned in the documentation, with the expectation of a significant speed increase.

I decrypt many messages in a loop and I get the following error messages after ~200 decryptions:
`Error decrypting message: Random number buffer depleted`

When I don't use web workers, I don't get these error messages.

However, before the errors, it seems that using web workers is faster than without them. Without web workers I don't see the expected 30x speedup of using native AES-GCM.

Any idea?

I use Safari 10.1 on macOs Sierra 10.12.4.

Thanks in advance!

 - Ed

**Comment by bartbutler** [comment]
Hi Ed,

Can you post your code? The random buffer thing can happen with too many concurrent messages (usually encryption rather than decryption), because the request for more random bytes happens after the request completes, so if to many requests are queued up you can deplete the buffer. We should maybe make this configurable.

The weird thing is that in the current code AEAD protect and web workers I think are mutually exclusive--if you have AEAD protect on, it doesn't use the web worker at all (or shouldn't...). That actually might be what's going on--the buffer I think might be used with and without the web worker, but only the web worker replenishes it...hmmm.

**Comment by eboily** [comment]
Hi Bart,

I did create a sandbox to reproduce the issue. It seems to be present only in Safari (latest i.e. 10.1). I do **not** observe it on Chrome, Firefox or Opera (all latest version).

The attached code produces the following errors in Safari:

`Error encrypting message: Random number buffer depleted`
`Error decrypting message: Random number buffer depleted`

[pgp-sandbox.zip](https://github.com/openpgpjs/openpgpjs/files/1071314/pgp-sandbox.zip)

To use the code, just open the index.html file in Safari and observe the dev's console for logs and error messages. You may have to put the code on a server since there may be a security error (DOM Exception 18) with the web workers if you open directly from the filesystem.

Thanks!

**Comment by eboily** [comment]
Hi Bart,

Did you have some time to look into the depleted buffer with/without the web workers?
