### ISSUE TITLE
Request: tree-shakeable ES6 distributable modules

### ISSUE THREAD

**Issue by axefrog** [openpgpjs/openpgpjs#547]
Any chance you guys could provide a tree-shakeable ES6 build in the dist folder? In other words, I already have a build system, as do many others who use Webpack 2 or Rollup. By transpiling to ES5, you're supporting people with older setups, which is great, but the rest of us have to suffer the huge build size unnecessarily. Even people using older setups are still often going to be doing their own transpiling, which means there's no need for you to do that for those people either.

The code already uses ES6, so it'd be great if you could simply build a non-transpiled version out to the dist folder as well, and provide an esnext module entrypoint in the package.json file. By doing so, users can import just the parts they need, and the rest can then be discarded during build, resulting in a much smaller bundle size.

**Comment by ellis2323** [comment]
I'm using the verify part of your PGP product and i would love to reduce the 350ko needed.

**Comment by bartbutler** [comment]
The main issue with this is the web worker. In fact, if you are importing into your project using web pack you are probably inflating the size of your project also because you are duplicating openpgp.js in your bundle as well as having your clients separately download it for the web worker.

We haven't really found a great way to fix this. There might be one with clever use of blob URLs but it's kind of a mess and involves running eval on a huge string, which messes up debugging badly. That's why the recommended solution is the current one--keep openpgpjs outside your bundle as an external dependency, the browser then downloads openpgp.min.js once, and both the main context and the worker context use the same file.

And yeah, running without the web worker is a recipe for warnings about scripts taking a long time, so that's not really an option either. We are trying to do some pruning and updating so we can streamline the size of the package but I doubt it will ever be considered small.

**Comment by twiss** [comment]
This is fixed in #1047, and will be in the upcoming V5 release :)
