### ISSUE TITLE
How to use with firefox webextensions? (if possible)

### ISSUE THREAD

**Issue by matteke-games** [openpgpjs/openpgpjs#599]
Hi,
I'm developing a small addon for firefox to encrypt/decrypt my webpages. But I cant seem to use openpgpjs since webextensions dont support "require". I was wondering if someone knows a way to get it working? If it is possible

**Comment by bartbutler** [comment]
When OpenPGPjs is built for browser, the requires are all replaced and final bundle is runnable in any sufficiently modern browser. It seems like you are trying to run it unbuilt/node-style.

**Comment by tomholub** [comment]
As Bart said. Download the bundle from https://github.com/openpgpjs/openpgpjs/blob/master/dist/openpgp.min.js

Since it's an extension, you want to list `/path/to/openpgp.min.js` as the first content script, then the last content script will be `app.js` or whatever your main script is. This script will have `openpgp` accessible as a global variable, so you can do:

```
var privKeyObj = openpgp.key.readArmored(privkey).keys[0];
// ... etc
```

You don't need `require`. Include the bundle the way you would include any other javascript file.

**Comment by matteke-games** [comment]
Aah, I was using a background script which called another script where I put require("openpgp"); since I thought I had to do it like that. doing what you said solved it, thank you :)
