### ISSUE TITLE
automate / clarify / standardize tests that include the web worker

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#609]
Following up from https://github.com/openpgpjs/openpgpjs/pull/604

> Any resources on how to run tests that include the web worker?

> I've been sort of faking it by fooling the saucelabs tests into running locally, but it's hacky. I think that's one of the things that needs some work.

Are the web worker tests somehow fundamentally different in the way they are orchestrated that it requires this? Is this because of way saucelabs works?

It would be good if anyone could do these tests locally as they develop instead of having to rely/wait for saucelabs for results (even when fixed). Eg I would imagine a shell script (ubuntu?) that would run the tests through node, latest Chrome and latest Firefox, each with and without web worker. This would cover a decent surface, and saucelabs would catch the rest.

Possibly better solution: a node script that would take the modified sources, pack them up and send to saucelabs to test - before commit - and print the results. People could contribute with more confidence, plus this will free up your time because you won't have to spend it fixing unexpected test fails. 

I recall there were some timeouts during these tests - these would have to be solved as well for this to really work well.

Just thinking out loud.

**Comment by bartbutler** [comment]
Hi @tomholub,

Yes, nodeJS does not support web workers, so the typical tests you get by running 'npm test' do not cover workers. 

To explain further, it might help to give a bit of a history lesson. OpenPGPjs tests used to use PhantomJS as a browser stand-in, and this worked well for finding obvious worker-related bugs, but it was limiting in some ways (the latest version at the time didn't support some critical features like Typed Arrays) and it didn't test any real browsers, so we were fairly often releasing new features that broke some random only version of Safari, for instance.

To fix this, @evilaliv3 did a bunch of work to set up SauceLabs and run automated tests with real browsers in Selenium via Travis CI. This was a huge improvement, as we could finally predict if a release would break browser compatibility or not. But it meant giving up local web worker tests because we ditched PhantomJS.

SauceLabs basically opens a browser window that runs the tests. There's more complexity than that but you can run it sort of locally by running 'grunt saucelabs' and opening a browser window pointed at localhost:3000/tests/unittests.html while it's running. It runs the 'connect' node web server and then tries to connect to SauceLabs, which fails. Adding another test target to just run 'connect' and wait until killed with Ctrl-C should be easy and is being worked on now, so in the future people can do local browser tests easily.

For automated worker tests though, I'd like to to look at PhantomJS again. It's been a year or more and it's possible the feature-set dealbreakers are gone. If so, we can add PhantomJS to the local tests to catch generic worker bugs and then rely on the SauceLabs tests via CI to catch anything that is browser-specific.

**Comment by mahrud** [comment]
@tomholub the recent merge includes a `grunt browsertest` feature that addresses this. Here's the snippet from README.md:

> For debugging browser errors, you can open `test/unittests.html` in a browser or, after running the following command, open [`http://localhost:3000/test/unittests.html`](http://localhost:3000/test/unittests.html):

     grunt browsertest

We can either close this issue or keep it open for tracking work on PhantomJS.

**Comment by tomholub** [comment]
@mahrud thanks for the update! Up to you - whatever you prefer.

**Comment by tomholub** [comment]
Recently I've got a lot of mileage out of https://github.com/GoogleChrome/puppeteer as a way to test things in the browser. It's packaged with its own browser which starts / stops automatically and it was very robust in my experience. It's robust enough that it could be included in the standard tests when you run `npm test`. It installs just like other dev dependencies with npm.

**Comment by tomholub** [comment]
Can run headless, too.

**Comment by twiss** [comment]
The worker has been removed in #964.
