### ISSUE TITLE
Unify BN libraries

### ISSUE THREAD

**Issue by bartbutler** [openpgpjs/openpgpjs#631]
Eliminate jsbn in favor of one of the modern BN libraries, probably BN.js or asmCrypto's bn library. Need to do appropriate benchmarks first:

https://peterolson.github.io/BigInteger.js/benchmark/

**Comment by mahrud** [comment]
ECC functions use BN.js already, so using that might help with keeping the bundle small.
Other than that, only RSA functions need bignums, and there's an issue open to use asmCrypto's RSA modules: #423.

**Comment by mahrud** [comment]
I added asmCrypto's library to @peterolson's BN benchmarks. Run the results [here](https://mahrud.github.io/benchmark/).

Looks like for our purposes, namely multiplication and squaring of large numbers, asmCrypto blows everything else away by multiple orders of magnitude. After that, bn.js seems better than the others.

**Comment by mahrud** [comment]
In case we do decide to go with asmcrypto, I made a branch [feat/asmcrypto](https://github.com/openpgpjs/openpgpjs/commits/feat/asmcrypto) that uses a minimal asmcrypto bundle for AES and SHA256 and bignum (I can later add RSA as well, but I'm not sure which specific RSA modules we need).

I decided not go with asmcrypto-lite because it's outdated and making a minimal asmcrypto bundle is as easy as adding and removing 11 lines now: https://github.com/mahrud/asmcrypto.js/commit/32ab996fac3e9bff62a53ce279c72f483a66771e

One potential thing to worry about is the size. asmCrypto is significantly faster but it seems to be bulkier than counterparts.
