### ISSUE TITLE
ignore_mdc_error: add warnings to decrypt result

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#651]
We like to use `ignore_mdc_error` for compatibility, but at the same time, we like to show a big fat warning to the recipient that the sender should upgrade their software when there is mdc error.

Current workaround is to try to decrypt with `ignore_mdc_error=false` first, detect mdc error, show warning to the user, set `ignore_mdc_error=true`, decrypt again and display the message. 

This works in a single iframe, but once we start decrypting more than one message per page (or use background process), dynamically changing config will affect other messages - not desirable.

Ideally, I'd like to set `ignore_mdc_error=true` and leave it that way, and then get a warning or flag as a part of the object I get back from `decrypt` methods.

Either `{..., warnings: ['mdc_error'], ...}` or more flexibly `{..., flags: ['mdc_error'], ...}` or something of that sort.

Later on, this could potentially be used for other kind of warnings, eg deprecated algos, keys considered very small by today's standards, etc.

**Comment by bartbutler** [comment]
I like the idea of a warning or flag list to communicate this kind of thing. Feel free to make a PR.

**Comment by tomholub** [comment]
Great, I'll do an OpenPGP.js sprint sometime along with a few other issues

**Comment by mahrud** [comment]
An alternative, in the spirit of ESLint settings, is to have three options for `config.ignore_mdc_error`: 0/false means ignore, 1 means warning, 2 means error.
This is backwards compatible since 1 and 2 have the same truthiness.

**Comment by tomholub** [comment]
You will only notice the warning if you look for it. Only on ignore=true,
else it will fail like before.

Adding an object attribute is I think considered backwards compatible. Let
me know what you think.

**Comment by tomholub** [comment]
Another potential warnings approach from https://github.com/openpgpjs/openpgpjs/issues/819#issuecomment-450877046

**Comment by twiss** [comment]
(Responding here because this issue is still open.)

> We could (…) throw if there were any warnings present, unless the developer called `ciphertext.getWarnings()` beforehand

That seems slightly magic to me - a function called `getWarnings` shouldn't have side effects IMO (although you could just name it something else so this is just a nitpick). However, I do like that the solution is more localized than a config option (so that if you have two calls to `decrypt` in your code you can't forget to handle one of them).

Another option would be to allow setting a sort of "warning handler" function, something like `message.onwarning = function(err) {}` (and have that function `throw err` by default). Or, co-opting `EventTarget`:

```js
message.addEventListener('warning', function(evt) {
  evt.preventDefault();
});
```

This has the added benefit that we don't have to store warnings in an array somewhere and then throw unhandled ones later, we can just call the handler function immediately and throw if it doesn't handle the warning.

All of these solutions are difficult to get working with the workers, although there are [unrelated reasons](https://gitter.im/openpgpjs/openpgpjs?at=5c2c8509f6166a3027a85d9e) to get rid of those (or move that functionality to a separate library).

---

Taking a step back though, MDC warnings can be quite serious, as EFAIL shows and [the spec describes](https://tools.ietf.org/html/rfc4880#page-83).

While the spec says `the implementation MAY allow the user access to the erroneous data`, I would personally prefer to move towards removing support for non-MDC messages entirely at some point. Although since you want this fixed your position is probably that there are still too many non-MDC messages out there, which is fair, and fixing this issue would definitely still be a step forward. Do you happen to have an opinion on a time frame in which removing support would be feasible?

Also, MDC warning are in a bit of a different ballpark than the warning in #819 — for the latter, the spec says `the implementation SHOULD decrypt the message anyway`, so it seems perhaps unwise to lump the two together in a single mechanism. For example, we don't want users ignoring the latter warning to accidentally open themselves up to EFAIL-type attacks by ignoring the former. (OTOH, the spec also says an implementation `MUST warn the keyholder that the protocol has been violated` in the latter case, so if we're clear on that and the application developer does so, this mechanism is indeed acceptable for both cases.)

**Comment by tomholub** [comment]
Agree that `getWarnings` as described is a bit too magic. Better naming may help, like `handleWarnings()`. But it's somewhat complex. I do like the simplicity of providing a warning callback as you suggested. Is it feasible & reasonable to throw if a callback was not provided and there's a warning? That sounds like the best of both worlds.

It's true that no-mdc is a serious warning when compared to some other warnings, if you consider security implications. `config.ignore_mdc_errors = true` could, instead of ignoring mdc errs completely, turn such errors into warnings. Warnings would still need to be handled with the callback.

------------

We did not plan to sunset decrypting MDC-less messages in the next 5 years. I wish we could, but slow moving institutions still rely on it. We do make the user jump through a lot of hoops and alerts to actually decrypt such message, and for that the warning mechanism is useful.

If no-MDC support was eventually removed from OpenPGP.js, we would probably ship our software with two versions of OpenPGP.js, one for regular use and one specifically when user requests to decrypt non-MDC. Either that, or maintain a fork.

What is the primary driver behind the motivation to remove it?

**Comment by tomholub** [comment]
I just saw you mentioned throwing err when no callback provided. Same thing I was thinking. I just want to clarify that we are talking about setting the handlers on individual instances, not the class, eg in `message.warningHandler = ...` or `message.addEventListener ... ` the message is an actual individual Message or PlaintextMessage object.

I'm not sure which of the two handling mechanisms is better. `msg.warningHandler = ` looks simpler, just replaces the default throwing method with something else. On the other hand,
```js
message.addEventListener('warning', function(evt) {
  evt.preventDefault();
});
```
allows to set several listeners, one of which may prevent the default (to throw), which is more flexible and explicit. I'm not sure we need that level of flexibility here. 

Both approaches look ok to me.

**Comment by twiss** [comment]
> I just want to clarify that we are talking about setting the handlers on individual instances, not the class

Yeah, that's indeed what I meant. I think both would be relatively simple to implement, barring the worker issue. If we also want to support workers in combination with this, `message.warningHandler` might be easiest, as we'd have to implement either API manually on top of `postMessage`/`MessageChannel`.

> It's true that no-mdc is a serious warning when compared to some other warnings, if you consider security implications. `config.ignore_mdc_errors = true` could, instead of ignoring mdc errs completely, turn such errors into warnings. Warnings would still need to be handled with the callback.

Good idea 👍 

> We did not plan to sunset decrypting MDC-less messages in the next 5 years.

Alrighty, understood.

> What is the primary driver behind the motivation to remove it?

Mostly the security implications :) Plus a sort of general feeling that folks are setting the config option to get rid of an error, without fully understanding the security implications or showing the user a warning. But I actually like the plan laid out above in this regard; hopefully the soft backwards incompatibility (with a clear and easy upgrade path) will give people some sort of reminder to actually show these warnings to their users.

Do you have time/plans to work on this?

**Comment by tomholub** [comment]
I also don't feel particularly bad about breaking legacy code where processing non-mdc messages stops working with OpenPGP.js upgrade. If we word the warning right, people who weren't aware of the risks before may become aware.

On our end https://github.com/openpgpjs/openpgpjs/pull/753 has priority over other things, and I'll have to work on that. Having a warning mechanism ready would come handy for that pull request too.. then there wouldn't have to be a config option.. mmm... :)

My spare time is unreliable. I cannot make specific time commitments. If lack of warning mechanism is not blocking other progress in the next 3-6 months, then I'll take the responsibility, and will get it done on one unspecified day in the future.

**Comment by tomholub** [comment]
> Yeah, that's indeed what I meant. I think both message.warningHandler and message.addEventListener would be relatively simple to implement, barring the worker issue. If we also want to support workers in combination with this, message.warningHandler might be easiest, as we'd have to implement either API manually on top of postMessage/MessageChannel.

I'll go with the `warningHandler` because we rely on workers. It will make them a lot simpler to support, less code to maintain, etc.

**Comment by tomholub** [comment]
I'm having second thoughts about this. The API is a little weird to use. Original:
```js
openpgp.config.ignore_mdc_error = true; // errors ignored
const options = { message: await openpgp.message.read(encrypted), passwords, format: 'binary' };
const { data } = openpgp.decrypt(options);
render(data);
```

Now becomes, for example:
```js
openpgp.config.ignore_mdc_error = true; // will still trigger warning
const options = { message: await openpgp.message.read(encrypted), passwords, format: 'binary' };
let hadMdcWarning = false;
options.message.warningHandler = function (warning) {
  if(warning.id === 'no_mdc') {
    hadMdcWarning = true;
  } else {
    throw new Error(`Warning: ${warning.message}`);
  }
}
const { data } = openpgp.decrypt(options);
render(data, hadMdcWarning);
```
It gets ugly really fast. Plus this particular issue could be solved less invasively:
```js
openpgp.config.ignore_mdc_error = true; // developer should check for warnings proactively
const options = { message: await openpgp.message.read(encrypted), passwords, format: 'binary' };
if (options.message.hasMissingMdcSecurityWarning()) {
  render('Security threat: ..., decrypt anyway? [yes, no]'));
} else {
  const { data } = openpgp.decrypt(options);
  render(data);
}
```
Maybe that's too specific and could be generalized..
```js
openpgp.config.ignore_mdc_error = true;
const options = { message: await openpgp.message.read(encrypted), passwords, format: 'binary' };
const { data } = openpgp.decrypt(options);
const warning = options.message.getSecurityWarning();
if (warning) {
  render(`Security threat: ${warning.message}, ..., render anyway?`));
} else {
  render(data);
}
```
Where the `getSecurityWarning` would be a simple method checking for problems, eg:
```js
Message.prototype.getSecurityWarning = function() {
  if(this.packets.filterByTag(enums.packet.symmetricallyEncrypted).length) {
    return { type: 'noMdc', message: 'This encrypted message is missing integrity protection (MDC). Rendering this messages can be VERY dangerous. Please ask sender to update their software to fix this security flaw.'};
  }
  if(this.other === 'problem') {
    return { type: ..., message: ... };
  }
  return undefined;
}
```
Good: don't have to worry about web worker. Simplified api
Bad: cannot "force" developer to check warnings

**Comment by twiss** [comment]
> ```js
> Message.prototype.getSecurityWarning = function() {
>   if(this.packets.filterByTag(enums.packet.symmetricallyEncrypted).length) {
>     return { type: 'noMdc', message: 'This encrypted message is missing integrity protection (MDC). Rendering this messages can be VERY dangerous. Please ask sender to update their software to fix this security flaw.'};
>   }
> ```

I somehow didn't realize that this way, it's pretty trivial to detect that the warning will happen before even trying to decrypt. So this code example then makes me think that the best way forward is just to implement it outside OpenPGP.js:

```js
openpgp.config.ignore_mdc_error = true;
const options = { message: await openpgp.message.read(encrypted), passwords, format: 'binary' };
if (options.message.packets.filterByTag(enums.packet.symmetricallyEncrypted).length) {
  render(`Security threat: ..., render anyway?`);
} else {
  const { data } = openpgp.decrypt(options);
  render(data);
}
```

Otherwise, we're pinning ourselves down to an API that is probably more complex than needed for this warning, and might accidentally be _less_ complex than needed when we ever want to give a warning that actually happens during decrypting, like an MDC mismatch.

**Comment by tomholub** [comment]
You voiced what was in my mind when I was investigating the code and writing the comment above. 

I was thinking `I could just do this in userland, anyway`.

I'm closing this. Folks in my situation will probably be able to google this. Thanks!
