### ISSUE TITLE
"Error: Unknown ASCII armor type" for armored message

### ISSUE THREAD

**Issue by ssky21** [openpgpjs/openpgpjs#652]
I am trying to use openpgp.js on my client to decrypt messages that are stored on my server.

One of these messages that have been returned looks like this
`-----BEGIN PGP MESSAGE-----\\r\\nVersion: OpenPGP.js v2.6.2\\r\\nComment: https://openpgpjs.org\\r\\n\\r\\nwcBMA17xrkVpOD7kAQgAjODlDXTb6NnTATVCuavw4NFBUM/6Upa/KVnwcHMH\\nqJ1QZHiULnfTiUlrTGi6GGRz8EBd1feJzAdy3UTIm7er2Q8mv8aRI5qhBWfG\\ngiE8kAV7qF6VpZ YQ ogst1k3WUz3QKjYl3yQutYPN4GUzRDA3afI89iuiGo\\neVxc1JNofRBG28djx9lL8W6V2stPwNJaF0frvWZlG51LVei96vCjWyM/lXj7\\nBQAdMolDA2UVnwJgbCbj2KhwnGWZUGoVeQ5C7/mYhTq ASeFxmmXyKg0ag0h\\nC152fJfknfbJ6y8KDtscn6pDUNk8q3KrUJrHDLGy2daxje/dVEBDlLxQ0UJF\\n0NLAqQFtEWbPZOvTpMA7OrX3xEZweRoAKzCyuh2tvCejFMYcobiHf1ISLvVb\\nQ6AWl2W KnSFiuRIcs/TcQofc0CXC9U6NhZh9i6LXm91/pM36/CxNO0vYICA\\ndqd1 k ohkzvktyPEsLwMgc9gWu1B6Yjlr2Nzr/kPcWWDXZEf6YeoPcxkHmn\\nzZzxHcWrlysETfmgy/v53xiohDEU9KySO84 CEKy1WcgXAE80e3LxTtlRmqx\\naSKQE1hCPObIB/Q9QMQx6yJ8HqAqFc1y3FiI53cr8zSbUwmsowCRG2s0c7ZZ\\nn6TOmhXwvUhd7530ZAMjsn5i74qMrPkexLkjA/S gvY1sU3iksM9RzfaWXlr\\nLHd0Y9K4BgTBSLi08jbE2B2YqbKITXRF3gk5N7BVkm6RmICU o0GVEvMbTZz\\nOOF8kORos3wGEgtPtDZiAV4POVTaY QdyAyC8Rjnd6Vk/HDXQ9WHi8plnJK/\\ntpgsQsY":"\\r\\n=3JGN\\r\\n-----END PGP MESSAGE-----\\r`

when trying to `message: openpgp.message.readArmored(encrypted),     // parse armored message`
I get the "Error: Unknown ASCII armor type".

Is this a problem because of the linebreaks? Do I have to format the message string differently?

**Comment by tomholub** [comment]
It's more than just the linebreaks. It's a mess. See any pgp message out
there and try to get it to have similar format.




On Feb 19, 2018 03:51, "ssky21" <notifications@github.com> wrote:

I am trying to use openpgp.js on my client to decrypt messages that are
stored on my server.

One of these messages that have been returned looks like this
-----BEGIN PGP MESSAGE-----\\r\\nVersion: OpenPGP.js v2.6.2\\r\\nComment:
https://openpgpjs.org\\r\\n\\r\\nwcBMA17xrkVpOD7kAQgAjODlDXTb6
NnTATVCuavw4NFBUM/6Upa/KVnwcHMH\\nqJ1QZHiULnfTiUlrTGi6GGRz8EBd1
feJzAdy3UTIm7er2Q8mv8aRI5qhBWfG\\ngiE8kAV7qF6VpZ YQ
ogst1k3WUz3QKjYl3yQutYPN4GUzRDA3afI89iuiGo\\neVxc1JNofRBG28djx9lL8W6V2stPw
NJaF0frvWZlG51LVei96vCjWyM/lXj7\\nBQAdMolDA2UVnwJgbCbj2KhwnGWZUGoVeQ5C7/mYhTq
ASeFxmmXyKg0ag0h\\nC152fJfknfbJ6y8KDtscn6pDUNk8q3KrUJrHDLGy2daxje/
dVEBDlLxQ0UJF\\n0NLAqQFtEWbPZOvTpMA7OrX3xEZweRoAKzCyuh2tvCejFMYcobiHf1ISLvVb\\nQ6AWl2W
KnSFiuRIcs/TcQofc0CXC9U6NhZh9i6LXm91/pM36/CxNO0vYICA\\ndqd1 k
ohkzvktyPEsLwMgc9gWu1B6Yjlr2Nzr/kPcWWDXZEf6YeoPcxkHmn\\nzZzxHcWrlysETfmgy/v53xiohDEU9KySO84
CEKy1WcgXAE80e3LxTtlRmqx\\naSKQE1hCPObIB/Q9QMQx6yJ8HqAqFc1y3FiI53cr8zSb
UwmsowCRG2s0c7ZZ\\nn6TOmhXwvUhd7530ZAMjsn5i74qMrPkexLkjA/S
gvY1sU3iksM9RzfaWXlr\\nLHd0Y9K4BgTBSLi08jbE2B2YqbKITXRF3gk5N7BVkm6RmICU
o0GVEvMbTZz\\nOOF8kORos3wGEgtPtDZiAV4POVTaY QdyAyC8Rjnd6Vk/HDXQ9WHi8plnJK/
\\ntpgsQsY":"\\r\\n=3JGN\\r\\n-----END PGP MESSAGE-----\\r

when trying to message: openpgp.message.readArmored(encrypted), // parse
armored message
I get the "Error: Unknown ASCII armor type".

Is this a problem because of the linebreaks? Do I have to format the
message string differently?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openpgpjs/openpgpjs/issues/652>, or mute the thread

**Comment by ssky21** [comment]
Yep I realized that ;) I stringified a response twice and then it tried to make an object out of a string and split it in the middle... Fixing that error solved my problem

**Comment by tomholub** [comment]
Great to hear, cheers
