### ISSUE TITLE
[Electron] Read private keys from a local GPG install

### ISSUE THREAD

**Issue by shibacomputer** [openpgpjs/openpgpjs#659]
I'm working on a small electron and would like to import private keys from the user's local GPG install (eg GPG Keychain on macOS) instead of generating and handling the keys within my own app.  I've done some research, and unless I'm totally missing something – which is likely – I can't seem to find examples or documentation of how to implement this.

Is this possible?

**Comment by tomholub** [comment]
Electron has a file system API. Read the file contents as a binary string,
then use openpgp.key.read to read that binary data - you will get a key
object.

On Mar 5, 2018 18:17, "Cade" <notifications@github.com> wrote:

I'm working on a small electron and would like to import private keys from
the user's local GPG install (eg GPG Keychain on macOS) instead of
generating and handling the keys within my own app. I've done some
research, and unless I'm totally missing something – which is likely – I
can't seem to find examples or documentation of how to implement this.

Is this possible?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openpgpjs/openpgpjs/issues/659>, or mute the thread

**Comment by shibacomputer** [comment]
Thanks for taking the time to respond to this. I worded my original question very poorly. I wanted to specifically know how to access a local `~/.gnupg/secring.gpg` to import a user's existing private keys. I ended up consulting with the core GPG team, who shot this idea down, and instead suggested I use `exec` and `gpg-connect-agent` to export the keys into a format that was readable by OpenPGP.js.

Closing this issue. I hope this helps someone else who might have a similar use case.
