### ISSUE TITLE
Possible to verify an encrypted message was encrypted with a given public key?

### ISSUE THREAD

**Issue by anarchistpenguin** [openpgpjs/openpgpjs#663]
I would like to validate that a message was encrypted with a given public key. Is this possible in the spec/this library?

Something like:

```
 let message = openpgp.message.readArmored(encryptedMessage) // parse armored message
 let publicKeys = openpgp.key.readArmored(pubkey).keys   // for verification

message.validate(publicKeys).then(function(verified) {
	validity = verified; // true
});
```

Apologies in advance I know this is not an 'issue'.

**Comment by bartbutler** [comment]
You can use the low-level API to look for public key encrypted session key packets in the encrypted message and then compare the key IDs with the key ID you are interested in. Something like:

`let packets = message.packets.filterByTag(openpgp.enums.packet.publicKeyEncryptedSessionKey);
for(let i = 0; i < packets.length; i++) {
  if (packets[i].publicKeyId.equals(publicKey.getKeyId())) {
    return true;
  }
}
return false;
`

This will have some level of false positives because key IDs are a subset of the key fingerprint and just are not that unique. Also, the OpenPGP spec allows key IDs to be zero as a method of preventing exactly what you are trying to do.

The 100% correct method is to have the corresponding private key and successfully decrypt the message, but that of course only works if you have the private key.

**Comment by anarchistpenguin** [comment]
Awesome. Thank you.
