### ISSUE TITLE
Inconsistent bit length on key generation

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#67]
Calling:

```
openpgp.generate_key_pair(1, 1024, 'a@bc.de', '12345')
```

Produces keys of either 1024 or 1023 bit size. Same applies to 2048 and 4096: in around 50% of the cases we get only 2047 or 4095 bit keys.
##

**Comment by tanx** [comment]
This issue seems less relevant as we use native RSA keygen in most cases. But I'll keep it open for reference.

**Comment by mahrud** [comment]
Ahah! I think I got it. This is in the random prime generator of jsbn.js:
https://github.com/openpgpjs/openpgpjs/blob/e939d9b1ab6aa44b6eadb525554ab9bf961439e8/src/crypto/public_key/jsbn.js#L882-L884
I think the reason why roughly 50% of the time the bit length is different is due to the original parity of the random number.
