### ISSUE TITLE
Performance: openpgp.message.readArmored should also accept Uint8Array

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#671]
This involves 
https://github.com/openpgpjs/openpgpjs/blob/e4c98a764f84b64372d07389cdd53e9df06647da/src/encoding/armor.js#L261
And more places where the data is treated as a string.

Motivation: PGP/MIME messages can get quite huge (attachments). Often armored. We download them as Uint8Array. Currently, we have to convert them from Uint8Array to string if we want to use `openpgp.message.readArmored`, which can unnecessarily degrade performance.

We may do a PR onde day if nobody objects to this.

**Comment by FocuzJS** [comment]
This is similar to my issue: #579 
Maybe you could include my fix in the PR in order to support Uint8Array data universally to avoid pushing strings to heap, especially passwords if you can help it!

**Comment by twiss** [comment]
I'm cleaning up the issues a bit, and if you don't mind, I'll close this one. You may have already thought of this in the meantime, but if you have control over the server, it might be better to unarmor the message server-side, and then send it to the client in binary. Armoring is fundamentally only needed when the transfer medium is text, and I feel like the added overhead of converting from Uint8Array to string when it isn't (especially now that we have the native TextDecoder API) is minimal compared to the bandwidth overhead of the armoring itself, to the point where I feel like rewriting the armoring parser to use Uint8Arrays instead of strings isn't worth it, as the latter is much simpler.

**Comment by tomholub** [comment]
Unfortunately this doesn't address our usecase - these are email messages we didn't create, downloaded from email server we don't control. It's a pity I let this rot, but sooner or later, I'll have to have someone on our team improve this.

**Comment by twiss** [comment]
> Unfortunately this doesn't address our usecase - these are email messages we didn't create, downloaded from email server we don't control.

Fair enough. However, since this issue was created, we've also switched to using the `atob` function that's built into browsers for base64-decoding (#1044), which takes a string as input and returns a string as well (unfortunately). Despite the extra string to Uint8Array conversion that's needed afterwards, this is still faster than the implementation that we had before. So I'm actually not sure if providing a Uint8Array as input would speed things up any.

**Comment by tomholub** [comment]
Noted. No prob - when we're back to investing into performance, we'll either bump into this or we won't. If we don't, then you won't hear from me anymore on this issue :)
