### ISSUE TITLE
efail.de mitigation: discussion & MDC errors

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#706]
I suggest that larger OpenPGP.js users form a group to discuss the extent that OpenPGP.js is affected once the details are released, and coordinate about any updates if needed.

https://www.eff.org/deeplinks/2018/05/attention-pgp-users-new-vulnerabilities-require-you-take-action-now

@bartbutler @toberndo 

// edit: now released at https://efail.de/

**Comment by toberndo** [comment]
My analysis at the moment:

- the direct exfiltration attacks (3.1 Direct exfiltration) in the Efail paper are based on implementation errors in the email client that fails to properly isolate decrypted content from other MIME parts. This class of errors is outside of the scope of OpenPGP.js
- "crypto gadgets" attacks are based on malleability of plaintexts in CFB mode. Checks on authenticated encryption via MDC is done in OpenPGP.js since 2015: https://github.com/openpgpjs/openpgpjs/commit/2ee347154cd6c1982f668ca633a2f7b24721ea88#diff-3b63464d07605a6e77bb2c9a518bc25d That means for AES which is the only relevant cipher in all modern PGP implementations and the preferred symmetric algorithm in keys generated in recent years, OpenPGP.js will refuse to decrypt messages which are not protected with MDC. As long as you do not modify the default value `false` of the configuration flag `ignore_mdc_error`.
- exfiltration channels in HTML are only relevant on the application level when the decrypted content is displayed, therefore do not affect OpenPGP.js

**Comment by tomholub** [comment]
Thanks for the response, here is a somewhat related issue https://github.com/openpgpjs/openpgpjs/issues/651

**Comment by bartbutler** [comment]
So are we agreed that we add an option controlling whether tag 9 packets are supported and have it off by default?

**Comment by bartbutler** [comment]
Or I guess we just expand ignore_mdc_error to effectively remove support for tag 9.

**Comment by tomholub** [comment]
Sounds good to me. I would go as far as to `console.warn` a warning every time a message is decrypted with `ignore_mdc_error=true`, regardless if it affects that specific message or not. The warning could say:

> Rendering messages decrypted with MDC protection disabled may allow attackers to retrieve content of past messages. See https://efail.de/ and github.com/openpgpjs/openpgpjs/issues/706

Or something of that sort.

**Comment by craigphicks** [comment]
The EFAIL is particularly effective because it can surround every whole encrypted block B with chosen encrypted binary to yield ABC  which decrypts to "...<img src="...[plaintext of b]...">.  Yet it also has the limitation that it cannot further divide the encrypted block B.  Also, EFAIL depends upon plaintext of B being part of and HTML attribute value.  Attribute values have a choice of only three final delimiters: doublequote (") singlequote (') and space ( ).  So if every plaintext that is encrypted as a single block is prefaced by those three characters, then EFAIL cannot what comes after those characters.  (Call it an obfuscation string). Play round with this [sandbox](https://try.jsoup.org/%7E_nyXks5PuAs-zJeek8CVhpuAvtI) to see how that works.

I've written in more detail at [A Solution for Sending Messages Safely from EFAIL-safe Senders to EFAIL-unsafe Receivers](https://github.com/craigphicks/efail-safe-send-to-insec-recv/wiki)

The thing about new EFAIL reading-safe versions that somehow force or Strongly! advise to use MDC is that some readers won't update for years.  And that becomes the problem of the sender when their messages are exfiltrated.  Only if the message format is changed so that old readers can't read new messages ... but there are obvious drawbacks to that. 

That's why I think this sender-safe solution, even if its a bit ugly, is worth considering.  

Any implementation would have to be close to the encryption module, to avoid any mistakes aligning the obfuscation string with the encryption boundary start.  So I think it has to be inside the PGP module, actively checking that alignment is correct.  

I could spend some time on this if there were reasonable consensus that it was a worthwhile feature.  

Looking through the code it seems like the CFB-AES blocking encryption is being called form cipher/cipher.c and and being implemented in libgcrypt/cipher/rijndael.c .  Starting out by just covering CFB-AES might be OK if that covers 99% of all cases.

I'd be grateful for any critical feedback.

**Comment by toberndo** [comment]
@craigphicks OpenPGP.js by default is only creating messages with MDC. My understanding is that all relevant PGP implementations should at least support verification of integrity protected messages. Do we have any data on outdated PGP clients in use that do not verify MDC? I'm not sure it has major benefits to optimize the sender side with a security feature that is only relevant for outdated PGP clients (older than 10 years?) which do not fulfill the definition of a secure system anyway.

**Comment by tomholub** [comment]
I agree - outdated software will by definition not change magically, it will require.. an update.

If it requires an update, then it's sensible to fix it the standard recommended way - update the software to use MDC on all outgoing messages.

**Comment by bartbutler** [comment]
Hi @craigphicks ,

Thanks for sharing your idea. So, first off, I'm not sure your solution would work. @pbrunschwig  had a similar idea to yours for the related-but-different problem of an open HTML tag in a prepended MIME segment: 

https://lists.gnupg.org/pipermail/gnupg-users/2018-May/060373.html

He said that it was able to be circumvented very readily, though I don't recall how. I realize you are talking about mitigating a different efail vulnerability, but it stands to reason that this mitigation might not be sufficient there either.

Secondly, while I agree with @tomholub and @toberndo that this isn't the correct solution to the problem, I do agree with you that old clients are an issue that needs to be addressed. I think the solution though is moving as a community decisively towards AEAD encryption, which solves all these problems and more, and agree as a community on a timeline to sunset sending new non-AEAD messages, because as you point out, as long as we do that some clients will ignore the MDC check, but AEAD message will not be readable without an upgrade.

Your solution does not to me have any advantages over just pushing AEAD except that it could theoretically be backwards-compatible with current old clients, but I'm not sure that's completely a virtue in this case.

**Comment by craigphicks** [comment]
That's true.  But I would point out, just to maintain consistency, that the
sole purpose of my proposed solution is exactly to allow safe sending to
readers who might not have an EFAIL-safe setup.  I don't believe there is
any other solution which addresses how to safely send to otherwise
EFAIL-unsafe readers.

**Comment by craigphicks** [comment]
I certainly understand the reasoning for cold turkey removal of support for
EFAIL-unsafe clients or users who set their clients EFAIL-unsafely.

Your referenced mitigation seemed to act without regard to encryption block
boundaries.  Any such method is subject to vulnerability according to the
EFAIL researchers:

> Because of the properties of the CBC and CFB modes of operation, an
attacker can split a single S/MIME or PGP ciphertext into multiple parts
and exfiltrate each independently with separate HTML tags (but still in one
email). If one part contains quotes then only the residual plaintext bytes
in that part are missing. There is a whole zoo of techniques that the
attacker can use to exfiltrate the full plaintext despite these technical
obstacles.

Basically, the researchers claim that every single encrypted block B can be
wrapped in multiple psuedo-encrypted blocks A,C yiielding ABC such that ABC
decrypts to the attackers desired HTML string.  So for any mitigation
method that doesn't align with encryption block boundaries there will
always be some potential leakage (unless by incredible luck every
encryption block is protected individually)

To counter this the proposed method I described uses the (rather obvious)
strategy of placing attribute value delimiting characters ( ) (') (") at
the beginning of EVERY block.
The attacker has no control over the block boundaries.  The EFAIL attack is
then not just more difficult, it is completely mitigated; impossible.

It's so rather obvious in fact that I think it probable the researchers
thought of it but left it out knowingly because announcing a 100%
mitigation exists would deflate the claim - even if that mitigation is
rather tedious to implement.

**Comment by bartbutler** [comment]
Yes, I understood that it's not the same thing, which is why I said I had seen a similar idea to yours for the _**related-but-different**_ problem of an open HTML tag in a prepended MIME segment, which could apparently be circumvented, though I don't recall being told how.

And while technically mails sent with your method would be readable by humans, I don't think it's really a viable solution from a cost/benefit analysis, not to mention the fact that all the extra garbage would just be asking for bug reports. I'd much rather focus on getting the AEAD standard finalized and then sunset all the old packet types.
