### ISSUE TITLE
How to confirm that encryption + simultaneous signing is occurring?

### ISSUE THREAD

**Issue by jamesthrosby** [openpgpjs/openpgpjs#743]
Hey there,

I have a use case here, where I am encrypting a text file with someone else's public key (i have an FTP connection with this someone else, they require that I encrypt with their public key so that it can be decrypted with their private key). However, they also require that I sign the encrypted file with my own private key, so they can verify its from me with a public key that i have already given them.

My issue is, when I encrypt the text, everything seems to go through absolutely fine, and i have a resulting file of the form:

-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v3.1.0
Comment: https://openpgpjs.org
...
...
...
-----END PGP MESSAGE-----

however, I was under the impression that it should result in a signed message that has the slightly different format:

-----BEGIN SIGNED PGP MESSAGE-----
...
...
...
-----END SIGNED PGP MESSAGE-----

Would I simply use the 'verify' method to check that the signature worked, even though I didn't sign any cleartext? I had trouble finding an example of how the encryption works when you're including a private key to sign it with.

The code is as follows (where 'str' is the parameter that contains the string I wish to encrypt and sign):
```
async function encryptFile(str) {
  let pub = fs.readFileSync('./keys/jpm_test.asc', 'ascii');
  let sec = fs.readFileSync('./keys/secret.asc', 'ascii');

  let passphrase = process.env.PASSPHRASE;
  let privKeyObj = openpgp.key.readArmored(sec).keys[0];
  await privKeyObj.decrypt(passphrase);

  let encryptOptions = {
    data: str,
    publicKeys: openpgp.key.readArmored(pub).keys,
    privateKeys: privKeyObj
  };

  let eCipher = await openpgp.encrypt(encryptOptions);
  return eCipher.data;
}
```

**Comment by bartbutler** [comment]
SIGNED PGP MESSAGE is not a valid armor header IIRC, and because the signature is inside the encrypted data packet, no one can see whether the message is signed or not without decrypting, so there is not a different armor header for signed vs not. You are probably thinking of cleartext signing which uses the armor header SIGNED MESSAGE.

So basically, the message is signed if you provide one or more public keys. The promise will reject if signing fails for some reason, so if it succeeds you know it is signed. That said, if you want to test this yourself to be super sure, all you have to do is sign and encrypt to yourself and then decrypt and verify using your public key. Let me know if any of that is unclear.

**Comment by tomholub** [comment]
Correcting @bartbutler 's response above: 
> So basically, the message is signed if you provide one or more public keys.

Should likely say:

> So basically, the message is signed if you provide one or more **private** keys.

Note that the private keys have to be decrypted first.

**Comment by bartbutler** [comment]
Thanks @tomholub , yes I misspoke. I have corrected my original response.
