### ISSUE TITLE
Import ECDSA key

### ISSUE THREAD

**Issue by samuelmanzanera** [openpgpjs/openpgpjs#745]
Hello,

 I noticed openpgp.js enable ECDSA key generation which is awesome.

But i'm wondering if it is possible to import ECDSA private key and generate keys for encryption and decryption. 

Example: using Ethereum private key to encrypt/decryot information with openpgp

If you have any ideas, please to share

Thanks

**Comment by twiss** [comment]
If you have a PGP ECDSA key you want to use, you can do so just like with any other PGP key: https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-string-data-with-pgp-keys

Since Ethereum doesn't use PGP keys, there's no easy or obvious way to use them in OpenPGP.js. What are you trying to achieve?

And finally, ECDSA by itself is only for signing, not encrypting.

**Comment by samuelmanzanera** [comment]
I was trying to encrypt and decrypt data with openpgp.  mostly with the multi key encryption to allow many recipeint to decrypt if they have the right private key.

**Comment by tomholub** [comment]
At the moment, importing ECDSA keys from Ethereum is not supported in OpenPGP.js, and probably out of scope for the library.

OpenPGP format has a lot more going on in addition to the secret material. You would have to design / implement that yourself.
