### ISSUE TITLE
Please remove stream support from library, it make a lot of incompatibility.

### ISSUE THREAD

**Issue by snowyu** [openpgpjs/openpgpjs#760]
The stream ability should be implemented on a third-party library instead hacking.
The stream ability is a user case which we can not image. Some guys need it, and some not.

**Comment by tomholub** [comment]
That is why the library is versioned as v4+. Feel free to use v3+ library, fork it & maintain it.

The maintainers have already thought this through and decided that the upside is worth the incompatibility. What you're asking for is unlikely to happen. I'd close this if I were a maintainer.

**Comment by sanjanarajan** [comment]
@snowyu we will not remove streaming support from the library, because as you said, "some guys need it."

That being said, we understand that not everybody will use this feature, so we made an effort to keep the internal use of streams invisible to end users who choose not to use them. We also tried to keep the high-level API for v4 similar to the API of v3 whenever possible. Please take a look at the updated documentation and let us know if you have any questions, or, as @tomholub said, you can continue to use the v3 library.

**Comment by snowyu** [comment]
Yes, but you can do it with another library, such as : openpgp-stream. 
The `openpgp-stream` is a client(user case) of openpgp.

It will make it bigger and bigger if fill all thing in openpgp.

All right.
