### ISSUE TITLE
Unhandled Promise rejection on Reader stream

### ISSUE THREAD

**Issue by emilmuller** [openpgpjs/openpgpjs#784]
I am constantly being hit with this one on Chrome. It doesn't hurt me though, but somewhat annoying.

Happens when I await openpgp.decrypt(...)

Version 4.1.1

![image](https://user-images.githubusercontent.com/16109123/47165382-1e7d8680-d2fa-11e8-85fb-0ac117afac78.png)

**Comment by twiss** [comment]
This is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=465666. It is indeed annoying as it makes Pause on exceptions pretty unusable. Unfortunately there's probably not much we can do about it.

**Comment by hhyyrylainen** [comment]
This is very annoying when trying to debug my app.
Is there a security problem with using a version of openpgpjs that doesn't trigger the chrome debugger every single time? 

I was previously using openpgpjs `2.6.2`. I'm using the latest version of electron (`3.0.13`)

**Comment by twiss** [comment]
> Is there a security problem with using a version of openpgpjs that doesn't trigger the chrome debugger every single time?

Unfortunately, yes. Both 4.2 and 4.3 fixed a bunch of security issues that will not be fixed in earlier versions.

I've dug into this a bit more and I've found at least part of the issue. If you look at the code of `releaseLock`, it rejects an unrelated promise: https://github.com/whatwg/streams/blob/fcc26195bbd38b7ca45d25dd270e61ce8e8b2091/reference-implementation/lib/readable-stream.js#L1035

Which then causes Chrome to break. This should really be fixed over there, but it's easy enough for us to fix so I've done so. There are a few other places this happens which are harder to fix, such as `controller.terminate`, but I hope this at least fixes the issue for those not actually using streams.
