### ISSUE TITLE
Packetlist not parsed correctly

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#789]
I'm facing issues when migrating a private key backup mechanism from OpenPGP.js v2 to v4.
This works in a way that the content of a OpenPGP message which contains the following packets: 
```
List(6) [Literal, SecretKey, Userid, Signature, SecretSubkey, Signature]
```
is symmetrically encrypted with a randomly generated passphrase into a message:
```
List(2) [SymEncryptedSessionKey, SymEncryptedIntegrityProtected]
```
When I again decrypt this message with the passphrase I can see at https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/sym_encrypted_integrity_protected.js#L156
that the packetbytes are exactly as the ones of the original content, so it seems like the encrypt/decrypt process works correctly,
but after `this.packets.read(packetbytes)` the resulting packetlist is only `List(1) [Literal]` whith the literal packet beeing a stream and empty.

Here is some test code with a symmetrically encryped message and the code to read the content of the literal data packet and extract the private key packets: 

```
const pwd = 'en0874op7nhqu2gjfded71siig';

const armored = `-----BEGIN PGP MESSAGE-----

ww0ECQMIgbiGsQTKFjFg0sTDAYdHMAgeuiOkFv2KC4MO6wOuylN7Ots4nFV/
FMpQHkiFExZ/Am0CEJR4FQMb1RJBZoh87ewWyniWzoHbdaiLOsurFOOtwfox
EbNaRgKGQCLI/a6XJQ8VFKmSzz3zEe3iFuwFPn68fklJm3u0wCfdMqo1jUut
1WYc6piGerMTuWM77EFCZvcb6E5BBm3qtk3RNgz/CrHWJMD8Qe4sRhTCHyvb
MLgQCakmTvrUNvJpbkKr6vOBp9qarqij6aseWV7mx+A/aQ2og7aMrw5f8nl5
1LBbE/THUg1MHbp/DXTnRHwYSFrNTDDQYrgBNqxgQDqugLprQn/6CWbcconi
dDIDqGE4zKuuDXWWxzhDi8gBu6SJlbm04OTGCnedtsVEEbHXaEWat3OV+muZ
/YXQC1aMw8M1tkwMI2W/LCom/tJkjVdmwQwjaXkrMPvAyNpdEJFqUUx4t/kr
e+TZhPnnUi50/vjPU3ziKZGdmBrczMHhproQ1vijgvrDE33U8USREZhPjsJh
4F267AlfarnwFGjqbQL1P0wZK6Hax0aWKtgIImG2I9YkWss4E9iqhtcgXcmr
F5R/50jKcSD0qFts/8cstqwB7UppOGx3ni4Do3jbG7SiIdhcD71gaxpOtkL2
LfahodIHoK1Vq//w5FB7Fd62s0RIMeXuNtF7M1y0+IC68lzkImKFsDup+HjJ
qiN87CJDmPqDGpf7LIzVAcdWE+0yRitMCFiGa3QLZjE1WK8d8VxOsUbHRWpK
jqsFekzm6pE15KCKYpKzvWU25BZ/Z2/DmgBQOVI6Z+q2SllDpc+tlTgC0mSw
+5ET+OaSFlVbxfxT3ENCPQLR/VG6CAtYan1FzVtIbD5GJA2gwZjvtKEuOfgw
6evu5/aC1K5cTVG5UmFy7I+Ox1GqGuZsDy8sWITzC139MlyqBq3zFLYFQ3Nd
0J2NFgE6Kqc3amnAKkuUmunP1ZNFSuyqK1n1KBcBCcVkVs0uygk1K+go6y6l
Cp8EP2iOwivD1t65zG8uVMGeGnJKgLjhjMfehTpthFgNaN6gOYIs6jgm8per
hcIMufw05Fwud/hjE7McBepdr/NS7vimPjiwwyNrNmtIkXSAylff0sQNuL+P
a8m5iO7fVn1QYvqKqjXKD6FNyPJXJmx1pFZJ3HuDnKtT4WOpRrI0723333eX
Mrq2FmewvgKmFOzE1LaNJvBDrbKLHSxLjsN0wELIH66Ax7azBvecep6/RpJZ
1YWHYyWnhUwIFSj9yVkFy72lK0le0r08DM3TJonlcVYaItyedpupd/ThgkfQ
kELFrGPGfHR7vwAI1ECKyYbtzDuTM8m+E0t466fNdeS9pVG6IPwQV8nEibHl
HNnt3DyQpcNrsrM73dUvP0k1l/CH+Y0PSNth/ynrVEnlLNAEmEabVStpWG6q
alwdFSkNw6EnoWVakz/os8bqhOpCS2iqRhNNJCXOG9nM6QwRrCO38HHFDk9r
+h+A0cZMB8Wn7807G4awJ4FmLVaQKzDTWgaUUdxVuKo6ZK617U6L/1Vg5QCD
0HxLpoMi2YUCVGJnHsU8BVVNgbFToj18DQmdxf+WHkZZH+5JzXpoMFXXFW3/
dH8krE3ZDq7hWOhflIZy9DLZZ73A6g0q2lLGBoA/heLyIiuNgQ46WS6OvLbt
JCn/ICimz0yuqdzQb0D6aAjZVOT97irGkv3u5UQNVvAd+p08KOLedKuIm8VG
BF1ry/7r0Gf9heo/Bz0rOKsYiuxrSCJXx2xuyBxCiTNYopzwpM0sFeecU3Lp
LFoJ6nQrtrgFxRiyeG4xijRvUG/xW3i5kHQAm0xrP08k66VzzFe/5AhmIBie
0lNKmu97clVHASMPG/X0p+OJMF3yETyODwFJg5Ln8y28Kg==
=T/Di
-----END PGP MESSAGE-----`;


let message = await openpgp.message.readArmored(armored);
message = await message.decrypt(null, [pwd]);
// get content of first literal data packet
const text = message.getText();
// remove literal data packet
const keyPackets = message.packets.slice(1);
// re-create private key
const privKey = new openpgp.key.Key(keyPackets);
```

**Comment by twiss** [comment]
Yeah. This is a byproduct of streaming support. At the time when `packets.read` returns, we haven't read the literal data yet (since that's done during decryption) and therefore we also don't know yet what packets come after it. Instead, `message.packets.stream` is a stream with the remaining packets. So, instead you can do:

```js
// get content of first literal data packet
const text = await openpgp.stream.readToEnd(message.getText());
// get packets after first literal data packet
const keyPackets = await openpgp.stream.readToEnd(message.packets.stream, _ => _);
```

**Comment by toberndo** [comment]
This works with the provided coding. Great, thanks @twiss for the quick response!
When packets.read is supplied with a Uint8Array (which is the case here), we already know that we don't have a stream. So should we not have `packet.fromStream == false` for all packets, as we are in a non-stream scenario?

**Comment by toberndo** [comment]
I still don't understand the streaming part enough, but there has to be a point where my specific content of a SymEncryptedIntegrityProtected gets interpreted falsely as a stream. While in the non-streaming use case when we have one literal data packet inside SymEncryptedIntegrityProtected, then we can call message.getText() after decryption and get a string instead of a stream.
Would it be possible to apply `openpgp.stream.readToEnd` in `List.read(bytes)` for all packets if you see that bytes is a Uint8Array?

**Comment by twiss** [comment]
> there has to be a point where my specific content of a SymEncryptedIntegrityProtected gets interpreted falsely as a stream

The point where the packet bytes are converted to a stream is inside `packets.read`, by `stream.transformPair`. It's not really "falsely" though, it's intentional and it will automatically be converted back later if you use the high-level API.

> While in the non-streaming use case when we have one literal data packet inside SymEncryptedIntegrityProtected, then we can call message.getText() after decryption and get a string instead of a stream.

Are you sure? I think in v4 message.getText() always returns a stream after decryption if you use the low-level API.

> Would it be possible to apply openpgp.stream.readToEnd in List.read(bytes) for all packets if you see that bytes is a Uint8Array?

Yes, that'd be possible. Although for example `Message.prototype.verify` expects and uses `msg.packets.stream`, so converting the stream to an array and back would be a bit wasteful in this case. So one possibility would be to call `readToEnd` if `streaming === undefined` (but not if it's `false`, which would so to speak indicate that the higher-level API is being used).

If you want `message.getText` to return a string, that's also tricky, because `Literal.prototype.read` *also* sets `packet.bytes` to a stream even if you pass it a Uint8Array. So you need to call `readToEnd` on `packets.bytes` sometime after `packet.read`, which feels like a hack.

Alternatively, you could reuse `convertStreams` in src/openpgp.js, which recursively calls `readToEnd` on *all* streams in an object.

**Comment by toberndo** [comment]
>Are you sure? I think in v4 message.getText() always returns a stream after decryption if you use the low-level API.

Correct, I didn't see that. Thanks for the detailed explanation. Makes all sense to me now.
