### ISSUE TITLE
openpgp.sign() does not work with very long string (with newlines)

### ISSUE THREAD

**Issue by heri16** [openpgpjs/openpgpjs#801]
In openpgp v3 on nodejs, the behavior below can be produced:

Returns a signature that passes verification (on short strings) but fails on long strings:
```javascript
      const data = fs.readFileSync(FILEPATH_TO_SIGN, 'utf8')
      const privateKeys = [privKeyObj]

      // const message = openpgp.message.fromText(data)
      // return message.signDetached(privateKeys, undefined, new Date(), {}).then(sig => ({
      //   signature: sig.armor(),
      // }))

      return openpgp.sign({
        data,
        privateKeys,
        detached: true,
      })
```

Returns a signature that passes verification (short or long strings):
```javascript
      const data = fs.readFileSync(FILEPATH_TO_SIGN, 'utf8')
      const privateKeys = [privKeyObj]

      const message = openpgp.message.fromText(data)
      return message.signDetached(privateKeys, undefined, new Date(), {}).then(sig => ({
        signature: sig.armor(),
      }))
```

This line is to blame:
https://github.com/openpgpjs/openpgpjs/blob/7aef1db7efbbf060d9d0eb7485b52915e220d9ce/src/openpgp.js#L408

**Comment by twiss** [comment]
The issue is probably not short or long strings, but whether they have trailing spaces.

Your two pieces of code differ subtly: the first creates and signs a `CleartextMessage` (as you pointed out in the linked code), the second a `Message`. `CleartextMessage`s remove trailing spaces, `Message`s don't.

You should either both sign and verify a `CleartextMessage` (using your first code example and verifying `new openpgp.cleartext.CleartextMessage(data)`) or sign and verify a `Message` (your second code example).

Which one you choose basically depends on whether and how you're planning to send the data to the verifying party. If it's over a channel where trailing spaces may be lost, such as email, a `CleartextMessage` makes sense. Otherwise a `Message` should be fine.

--- 

All of that said, v3 is no longer supported, and moreover has a number of security issues that have only been fixed in v4, so please upgrade if you can.

v4 also forces you to pass a `message` object to `openpgp.sign`, just like `openpgp.verify`, which also prevents this kind of issue.
