### ISSUE TITLE
Minified content in distribution

### ISSUE THREAD

**Issue by douglasheld** [openpgpjs/openpgpjs#813]
Just taking a peek at the opengpgjs distribution, it appears lines 1-7 of the non-minified file have minified content.
Is this perhaps an error in the release process?

The apparently minified content starts on line 1 with `(function(f){if(typeof ...` and ends with `},{}],2:[function(require,module,exports){` on line 7.

**Comment by twiss** [comment]
The code you're seeing is the [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-adapter) dependency, which is pre-minified. This is because its [package.json](https://github.com/MattiasBuelens/web-streams-polyfill/blob/6a6d788ff587f9d528d3df2d04319064143834e6/package.json#L6) refers to `polyfill.min.js`.

This by itself is not a huge issue, but there's another downside with the way we're packaging web-streams-polyfill, because we're including their ES5-compatible build in both our ES5 and ES6 builds. Our ES6 build could be made smaller by either including their `@mattiasbuelens/web-streams-polyfill/ponyfill/es6`, as described in the [README](https://github.com/MattiasBuelens/web-streams-polyfill#usage), or by building it ourselves.

If you want to take a stab at improving the build process, feel free to.

**Comment by twiss** [comment]
(Closing this - 76ce33d96ba1cb4f7c0f8ddf57cfd6c250f03318 improved the situation a bit here, although there's still improvements to be made to the build process.)
