### ISSUE TITLE
Error decrypting message: A non-preferred symmetric algorithm was used.  

### ISSUE THREAD

**Issue by AndreEckner** [openpgpjs/openpgpjs#819]
I'm trying to decrypt a message that was encrypted with the GoLang-implementation of OpenPGP - so the keyPacket.sessionKeyAlgorithm seems to be "cast5".
But I always get the error **"Error decrypting message: A non-preferred symmetric algorithm was used."**

How can I add Cast5 to the preferred symmetric algorithms ?

In your 4.3 release note you state that one can do something like
**openpgp.config.symmetric = openpgp.enums.twofish**

But this is simply not correct:
- openpgp.config doesn't have "symmetric", nor is it mentioned anywhere in the config-API (https://openpgpjs.org/openpgpjs/doc/module-config.html)
- openpgp.enums doesn't have "twofish" - although this seems to be only a typo, I guess it has to be
"openpgp.enums.**symmetric**.twofish"

**Comment by twiss** [comment]
> In your 4.3 release note you state that one can do something like
openpgp.config.symmetric = openpgp.enums.twofish
> 
> But this is simply not correct

You're right. The correct syntax is `openpgp.config.encryption_cipher = openpgp.enums.symmetric.twofish`. However, this won't fix your problem.

Could you post the public key? What software did you use to generate it?

> I'm trying to decrypt a message that was encrypted with the GoLang-implementation of OpenPGP - so the keyPacket.sessionKeyAlgorithm seems to be "cast5".

That's a bit weird. From https://godoc.org/golang.org/x/crypto/openpgp/packet#Config, golang seems to use AES128 by default:

    // DefaultCipher is the cipher to be used.
    // If zero, AES-128 is used.
    DefaultCipher CipherFunction

Do you have access to the code that was used to encrypt the message?

Also, could you try decrypting the message with GPG? If it decrypts the message *without* saying something like

> gpg: WARNING: cipher algorithm CAST5 not found in recipient preferences

then it's probably a bug in OpenPGP.js. If it does give the warning, it's probably a bug in the sender's code. Although if this is a common issue, we might have to add a config option to ignore this warning.

**Comment by AndreEckner** [comment]
The PublicKey is
`-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: GnuPG v1\n\nxsBNBFwbaL0BCACi4VlElXgNTmRHb4/wZiH4WFSis6bhKxR1l+YST8UzesnAJA/P\nyi02I1BEEIlyeq7y1vMGKcNDqvxPGek8JnFrXiApLBwUgEyoa8xMCnVRGZ0GCuE7\nnuYiVuv3I1yPzr6h7pNUE55mnvX2lB1tT09OwYbDya8U54QXAv/xt9g8CWcBsrDu\nRdKsOLDUHdacXdoNYbxdnioPJGKIHBBNFhhnV8ZIeFSQRi7VrrX9zjsNBhFUl4j+\nYI/G5MPZaGrsdhOwIYqj1DT12CqIP3lMvT1C8ALRE8FDRF/eVDXs9av7Ciw9cbdK\nORYVhw48HkjgK9UB37A20+mfA4Vx0e1EeHyxABEBAAHNEUMuIE9zbWljIChjb3Nt\naWMpwsBiBBMBCAAWBQJcG2i9CRBMAPOMV7OaZQIbAwIZAQAA01UIAIwoHVtAlPBj\nsQhwHUq3bhmCoycgQv7XscczPmrtbeiMWakIwqw3SWSMWyslecL4V41v53PLfJmz\ntUm2eAG5x6pML6KWJK/P4JCRlvTvCcTG/4YHs2pW9XNKssdbuKPmCL9ruPV8C9aS\nmQEO3R2X5mxBpkCG2MDttmlCH8PhmYLr6Uc6jH3gWh4JkUk6yt/UAoAJGzXGI8Ij\nwr/uGDJek4JFIpg7UTJ3DUrPVpM6MxVZC84zEzRX2H/LxjNM4udQ1eBhZ34tMBnU\nd7T95WTTRgfssJz8iXuInjuC74kQuDcTtTsDlJQ6c/Vhn4eCdKT/12IGtnryDd0M\nikhWLJVkTCjOwE0EXBtovQEIAMWbC3ML+a0VDNj2RVVBwIB8s2IXkzWFoD2XO1qy\ndkPOuGQThAUz0uxsx2/e2aB5IIJ2VL4q7rIcpJGtUH7C/0vxvmhMti+TE44GS4wW\ndvYn344OeEM0jyn6E1SFSdHOt25eqm40oJiQuYcJ/lD28uRmlAjLVSjJlgDF9wGS\nLAnkH/8NixtZbgSNX/87TVkZDKDJN7f9SYOTn+6eom9mH4RQctIjZXc8oQKaQ5Vw\n8zyVzd/SdjwRJISWoW+lG7FO+BXx3sv6kWGYozUxvQUM4WvylELQ/MSe5iYPOV/n\n7IvFmqPrIPH6AceRJgqLBz8XLnw1pVLy+yjTLFi0qSDB2o0AEQEAAcLAXwQYAQgA\nEwUCXBtovQkQTADzjFezmmUCGwwAADR2CACNEP9uTLx+UebMcNc5QEFOzsFqj88k\neQqq323/9Em8OjTtge/Xd51CerIYP2+GWi4XaLIPOFu3aW6T4iY6387OEpp3zcfJ\nIz+G/WRuO9IvI4na8zi2ZVSfedEBjJmRtiF/ktdeYySapkTNHS9iXXSJlQuMJfFm\nGL/ptANvRL8BxM0VIWDmp4JibfMke29OkAowESej8Xg04Gsp27NVCtkoAklf9aAp\n1KZjcS3pAUhjP//rjN3SR2LXh6saMj6Qy6KwFequcGV1GyF4x0Ta55RNwiDmMjFK\nqjb8xwTB8hmMrnaEHEDhMSHsYqxNJulFkjV4ETfpAdxuhv20Z9pxjKer\n=GC3I\n-----END PGP PUBLIC KEY BLOCK-----`


When I try to do it with GPG directly: gpg --decrypt message
-->
gpg: WARNING: cipher algorithm CAST5 not found in recipient preferences
gpg: encrypted with 2048-bit RSA key, ID 1F91580C0BFF06F4, created 2018-12-20
      "C. Osmic (cosmic)"

**Comment by AndreEckner** [comment]
The Golang-Code seems to be the pretty generic:

`func (r *CryptoRSA) genKeys(login, name string) error {
120     var err error
121
122     conf := &packet.Config{
123         RSABits: defaultKeySize,
124     }
125
126     r.Entity, err = openpgp.NewEntity(name, login, "", conf)
127     panic_on(err)
128
129     return nil
130 }`

**Comment by twiss** [comment]
The public key is fine. It doesn't have any preferred algorithms, but that's ok, it just means the sender should use TripleDES or AES128.

Can I see the code to encrypt the message? (The code you posted was to generate a key, but actually I'm a bit confused - the public key you posted claims to have been generated by GnuPG v1, not golang?)

**Comment by AndreEckner** [comment]
Thank you a ton for your quick response! - I was able to find the culprit in my colleague's code:
He used the standard-encrypt-command without a config-Object:

plaintext, err := openpgp.Encrypt(data, openpgp.EntityList{r.Entity}, nil, nil, **nil**)

which, per Golang's OpenPGP-implementation defaults to Cast5 instead of AES256 :

`
func Encrypt(ciphertext io.Writer, to []*Entity, signed *Entity, hints *FileHints, config *packet.Config) (plaintext io.WriteCloser, err error) {
	[...]
	// These are the possible ciphers that we'll use for the message.
	candidateCiphers := []uint8{
		uint8(packet.CipherAES128),
		uint8(packet.CipherAES256),
		uint8(packet.CipherCAST5),
	}

	[...]

	// In the event that a recipient doesn't specify any supported ciphers
	// or hash functions, these are the ones that we assume that every
	// implementation supports.
	defaultCiphers := candidateCiphers[len(candidateCiphers)-1:]	

	**[some Code that overrides this with the value of Config.Cipher, if existent]**
`

So now my solution was just to change his code and use this:
`
plaintext, err := openpgp.Encrypt(w, openpgp.EntityList{r.Entity}, nil, nil, **&packet.Config{
	DefaultCipher:            packet.CipherAES256,
}**)
`

**Comment by AndreEckner** [comment]
Which... did work for about 5 minutes. Now it's the good old "non-preferred"-message all over again. -.-

I'll figure out what this is about and then report back here.

**Comment by twiss** [comment]
From reading through the Encrypt function, it seems like the reason that wouldn't work is 

```go
		preferredSymmetric := sig.PreferredSymmetric
		if len(preferredSymmetric) == 0 {
			preferredSymmetric = defaultCiphers
		}
		candidateCiphers = intersectPreferences(candidateCiphers, preferredSymmetric)
```
... and then it chooses `config.Hash()` only if it's in `candidateCiphers`, which at this point contains only CAST5.

So I think we should just add an exception for CAST5. Which is kinda ironic because then:

- TripleDES is always allowed because the spec says so
- AES128 is always allowed because the new draft spec says so
- AES256 is always allowed because it used to be OpenPGP.js's fallback (violating the spec)
- CAST5 is always allowed because it is golang's fallback (violating the spec)

And the only algorithms we support that are not always allowed is AES196, Twofish and Blowfish :) Oh well.

**Comment by twiss** [comment]
I don't think your use case is that weird :) IIUIC, you're just generating keys and encrypting to them with the default configuration with Golang's built-in library, and then decrypting them with OpenPGP.js. PGP is supposed to be interoperable, so this is definitely a valid use case. It's of course unfortunate that golang is not RFC4880-compliant by default in this regard, but neither is OpenPGP.js technically speaking (when using third-party-generated keys without preferences) since we implement the draft of the next version of the spec instead of the spec itself, so we can't really complain.

Furthermore, the spec calls for showing the user a warning in this situation, as GPG does, whereas OpenPGP.js throws an error, since OpenPGP.js doesn't have a mechanism for showing the user a warning, as it's a library instead of an application. (Perhaps we should have a mechanism for returning warnings in addition to the decrypted data, but application developers would probably just ignore them.) So I think it's reasonable to be less strict about throwing errors than GPG is about showing warnings.

**Comment by tomholub** [comment]
A warning mechanism would be great, it's something I wanted to do for MDC errors but didn't get around to doing yet. So thinking about a general mechanism would be really good.

One way to approach it would be to add a `warnings` field in responses where it makes sense, then by default fail on any warning.  Developer can switch `config.fail_on_warning = false` at which point it's the developer's responsibility to check for warnings proactively.
