### ISSUE TITLE
Clearsigned message not read by readArmor()

### ISSUE THREAD

**Issue by jgarzik** [openpgpjs/openpgpjs#825]
The data:
0) openpgpjs version 4.3.0 via npm on node 10.1.0.

1) gpg v1 signs a message using `--clearsign` on Ubuntu 16 LTS:
```
$ gpg --version
gpg (GnuPG) 1.4.20
...
$ gpg --local-user MY-EMAIL-ADDRESS --clearsign message.json
```

2) Using `openpgp.cleartext.readArmored` the following appended cleartext signed message is input with an apparently-zero-size signature, even though gpg is happy with reading and verifying the message.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{
	"verfToken": "45037b8d-5b6d-4b3d-959a-b5882c7ea89d"
}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIVAwUBXCBOBSWzCDIBeCsvAQLMmxAAtonipbMrxK1/16QbnJAeup6me7b97B1P
lycadFMRE0c91V9oLGMRI1xvrZnZrrxU4EJf/srOBLrmMTA0jsCu39Mxe9wRj4NY
Lyt1SjQXBXNy+haroJDXoaObHifOeSESjgijHLWvHJUBktR2ba4/FBBURwWHvgSN
yyu2LUsfi9r+IlLkW8kNTQK1xfO9ZcX8QcxCqYkANLo/GSu2R6rgcPHl/2PRgtsa
nhGwGOFX4HSnkvsb7YYUfRO7t3DGv7f/afJJOpQlxnm73VRbchROhOe9Uqgs7ttj
5yWJ1mrf3nweCyazYNWaAo6mRyL21Ry/RVwkdfK2EmWlSOc/Ph5920gnqx+B0c/D
dX8fDCBT+LMxFPZEJPixbels3Hbl/AhTkGjbeOwXxwBDzWaoXCU3+L0TOMfDCv+h
nb5v0728ujh+q6+JN4CuqBgjWHoIQrfHZQje63JqZmTU707mXzIrl24jkKH3QlyU
uojcpmVbbDdGklRrb8QYs8zKT/w1cUUIlUl2rW+l96Y2z8a1OqIaQuoSe5T2Zzb4
YlB15fGYztRyy1JTWRton1bK1/V2qWcYg1oPCuLqeZ92cq1dIpUu/BFcoJTDbywU
GlgV9USX7sdJMI4ufAMbl2xsNCbZkpLXEZSi/6SwTJydCPjFNIsdgT7HqaRUwGuS
Ly9ZqIvNvsY=
=yjAG
-----END PGP SIGNATURE-----
```

3) console.dir() output for the resulting CleartextMessage:
```
CleartextMessage {
  text: '{\r\n\t"verfToken": "45037b8d-5b6d-4b3d-959a-b5882c7ea89d"\r\n}',
  signature: Signature { packets: Array { length: 0, stream: null } } }
```

**Comment by twiss** [comment]
Hi @jgarzik! This is a version 3 signature. Support for v3 signatures has been removed in OpenPGP.js 4.0.0. (That release also fixed a bunch of security issues, so please don't use an earlier version, but instead try to get GPG to generate a v4 signature.)

There is a `--force-v3-sigs` option, do you have that in your options file perhaps? You can disable it with `--no-force-v3-sigs` or `--openpgp`, could you try adding one of those to the signing command?

Otherwise I'm not quite sure why GPG would generate a v3 signature, it has supported v4 for over two decades. Perhaps it does that if you have an old v3 key? You could try generating a new key and trying again.

You could also try upgrading to GPG 2.1.0, which also removed support for v3 keys and signatures.

**Comment by jgarzik** [comment]
Thanks for the response @twiss 

Looking at my `options` file, I see
```
# The next option is enabled because this one is needed for interoperation
# with PGP 5 users.  To enable full OpenPGP compliance you have to remove
# this option.

force-v3-sigs
```

So it seemingly wanted me -- at the time that options file was created years ago -- to remain compatible with older PGP.

If v3 signature support is being removed in GPG 2 and also OpenPGPjs, that sounds like a bad option to enable...

Closing ticket.
