### ISSUE TITLE
Signature is not checked on decryption with public key provided

### ISSUE THREAD

**Issue by jochenonline** [openpgpjs/openpgpjs#850]
I am encrypting a text with the public key of the receiver and the private key of the sender. So the message should be signbed. When I decrypt the message with the private key of the receiver it is meaningless which public key I provide to check the signature. The decryption is always successful. I expected it to work only if I provide the public key of the sender. Am I wrong?

**Comment by sanjanarajan** [comment]
Yes, this is expected behavior.

If the correct private key is used for decryption, decryption will succeed regardless of which public keys are passed in for signature verification. Whether signature verification succeeds or not can be found in the returned `signatures` array, which contains one entry per signature packet. 

```{
  data: String|ReadableStream<String>|NodeStream, (if format was 'utf8', the default)
  data: Uint8Array|ReadableStream<Uint8Array>|NodeStream, (if format was 'binary')
  filename: String,
  signatures: [
    {
      keyid: module:type/keyid,
      verified: Promise<Boolean>,
      valid: Boolean (if streaming was false)
    }, ...
  ]
}
```

The "verified" field should evaluate to true if and only if signature verification succeeds for the signature packet signed with the private key corresponding to the `keyid` field.
