### ISSUE TITLE
Can't generate detached signature form binary

### ISSUE THREAD

**Issue by raftario** [openpgpjs/openpgpjs#884]
Hi,
I've been trying to generate a detached key from a binary file for a couple hours now, and I can't seem to make it work.
Everytime, the output is the same :
```
-----BEGIN PGP SIGNATURE-----
Version: OpenPGP.js v4.4.10
Comment: https://openpgpjs.org


```
Just a header, no signature.
However, if I generate it from text it works, and if I set detached to false it works. Any ideas on that ?
Here is my code :
```javascript
const fs = require('fs')
const openpgp = require('openpgp')
let privkey
fs.readFile('./privkey.asc', 'utf-8', (err, data) => {
  if (err) console.error(err)
  privkey = data
  gen().catch(err => {console.error(err)})
})
const passphrase = 'super secret passphrase'

async function gen () {
  const privkeyObj = (await openpgp.key.readArmored(privkey)).keys[0]
  await privkeyObj.decrypt(passphrase)
  const signOptions = {
    message: openpgp.message.fromBinary(fs.createReadStream('./test.zip')),
    privateKeys: [privkeyObj],
    detached: true,
    streaming: 'node'
  }
  openpgp.sign(signOptions).then(signed => {
    signed.signature.pipe(fs.createWriteStream('./test.zip.sig'))
  }).catch(err => {throw err})
}
```

**Comment by twiss** [comment]
Hey :wave: Thanks for catching this. The reason this happens is that for streams, the data is usually signed simultaneously with being encrypted, or armored in the case of a non-detached signature, and so it waits for that. Since that never happens in the case of a detached signature, it gets stuck. I'll try to fix this for the next release.

As a workaround, you can do:

```js
openpgp.stream.readToEnd(signOptions.message.armor());
```

after the pipe and it will work.

**Comment by raftario** [comment]
Thanks for the workaround, works as expected now !
