### ISSUE TITLE
Signature verification fails due to slight difference in time

### ISSUE THREAD

**Issue by GHLover** [openpgpjs/openpgpjs#902]
I encountered a very strange issue. If a message was generated on one computer that had a clock set forward in time and that message was decrypted / sig verified on another computer with the clock set backward in time, then the signature verification fails.

**Reproduce**
Computer With Clock Set Forward In Time
1. Encrypt message and sign it for public key

Computer With Clock Set Backward In Time
2. Decrypt  message and verify signature

**Result**
The signature fails verification

**Expected Behavior**
The signature should still verify. **This is not a case where there is a huge time difference**. I am literally talking about 2 minutes in time difference. So, imagine someone emails someone who has a clock that is a few minutes behind. Anyone who tries to verify the message with a slow clock will get a verification error until their clock passes a certain point.

The only thing I can imagine is that a message / signature is timestamped with a particular time. And, the message cannot be verified until that time has passed.

If this is intended behavior (I cannot imagine it is imagine the use-case I just gave), then how can it be disabled?

**Comment by twiss** [comment]
Hey :wave: All signatures have two dates associated with them: a creation date and an expiry date. By default, the current date is expected to be between the two. Also by default though, signatures don't expire, so that just leaves the creation date check.

Both `openpgp.encrypt` and `openpgp.decrypt` have a `date` parameter. There's basically 3 approaches you can take to mitigate this issue:

1. Pass in `null` to `decrypt` to disable date verification entirely. This is not recommended as it also disables expiry checks.
2. Pass in a date object slightly in the future to `decrypt`
3. Pass in a date that you receive from the server to both `encrypt` and `decrypt`

**Comment by twiss** [comment]
(Lmk if you still have questions)

**Comment by GHLover** [comment]
Can you provide me an example? I am trying to do what you suggested, but it is not working. Here is the code I am using:

```
let args = {
    message: await openpgp.message.readArmored(msg),
    publicKeys: (await openpgp.key.readArmored(pubkey)).keys,
    privateKeys: (await openpgp.key.readArmored(privkey)).keys,
    date: null,
    format: 'binary'
};

let decrypted = await openpgp.decrypt(args);
let isSignatureVerified = false;
for (let i = 0; i < decrypted.signatures.length; i++) {
    if (decrypted.signatures[i].valid === true) isSignatureVerified = true;
}

You can see that the "date" parameter is null. I have looked at the examples and cannot find any examples. I also tried to pass a future date via passing "future" with this code and that also failed:

```
let now = new Date();
let future = new Date(+now + 86400*1000 * 7)
```

It is definitely a time issue because when I change the time of the signor to be less than the one receiving it, then it work perfectly.

**Comment by GHLover** [comment]
Nevermind, it works now

**Comment by L11R** [comment]
@GHLover I still get an error sometimes. What means "it works now"? Just SUDDENLY started to work? Doesn't you think that this is strange?
