### ISSUE TITLE
Import keys

### ISSUE THREAD

**Issue by jose123455587** [openpgpjs/openpgpjs#905]
Hi,
How about create a import keys feature,where we can import keys from a folder and read email,name,fingerprints and other things.
I think this would be awesome.

**Comment by tomholub** [comment]
Hello, this is likely out of scope, as it's probably a node-specific feature. You could implement this in a few lines of code, not sure why it would be a part of the library?

(I maybe have missed something though)

**Comment by twiss** [comment]
Yup. Or you could create a web page with a file input, call `await openpgp.message.readArmored` on the uploaded file, and display the details. This shouldn't be part of this library though, but could be a separate thing that makes use of it. Good luck!

(One way something like this could be included in this repo though is as a sort of "demo" page - but that would have as its primary purpose to show off openpgp.js, rather than to "be useful" - so I think that may not be what you have in mind.)
