### ISSUE TITLE
filterByTag check never throws due to List() truthyness

### ISSUE THREAD

**Issue by adhooaa** [openpgpjs/openpgpjs#907]
At [message.js:158](https://github.com/openpgpjs/openpgpjs/blob/master/src/message.js#L158) there is:
`    const symESKeyPacketlist = this.packets.filterByTag(enums.packet.symEncryptedSessionKey);
    if (!symESKeyPacketlist) {
      throw new Error('No symmetrically encrypted session key packet found.');
    }
`
However the implementation [filterByTag](https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/packetlist.js#L154) always returns a `new List()` (which may be empty).

Even when empty, `    if (!symESKeyPacketlist) {` always evaluates false because empty lists are still `truthy`

There may be other places in the code that follows this pattern...

**Comment by twiss** [comment]
Thanks, good catch! In this case, it shouldn't matter too much if that list is empty as we'd still throw a bit further down:

https://github.com/openpgpjs/openpgpjs/blob/43441bfe0d93f0dae4f2cc27232a170b2f20f750/src/message.js#L240

However, feel free to make a PR anyway, in order to improve the error message, and to fix any other cases if you find them.
