### ISSUE TITLE
signature verification hangs forever

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#916]
Streaming not used, verification happens in extension background script, plus it's using a web worker.
```js
      const verifyResults = await decryptedMessage.verify(keysForVerification, new Date(), false);
      console.log(23);
      for (const verifyRes of verifyResults) {
        console.log(24);
        x.push(await verifyRes.verified); // stuck here
        console.log(25);
      }
```
I think it started happening around the time that streaming was introduced.
Only happens with decrypted messages, does not happen when verifying plaintext.

The offending line in openpgp.js is:
```js
  const i = Math.random(); // debug
  console.log(`will hang: ${i}`); // debug
  hash = await _webStreamTools2.default.readToEnd(hash); // stuck here, never finishes
  console.log(`done hanging?: ${i}`); // debug
```

Example output:

![image](https://user-images.githubusercontent.com/6306961/60124932-3b683480-977a-11e9-832a-56c8fdf6c1dd.png)

Testing on Chromium.

**Comment by tomholub** [comment]
If I take the literal and signature packets and make a new message out of it, and verify that instead, it will verify properly without hanging.

**Comment by twiss** [comment]
My guess is that the issue is that usually, when a message is created from a stream (e.g. when it was just decrypted), OpenPGP.js verifies the message simultaneously with _reading_ the message. When streaming, this can be used to control the pace at which the message is decrypted&verified. When not streaming, the high-level API does this by returning the message data as `result.data`, but it's not happening here.

Specifically, you have to read the data _after_ calling `verify` but _before_ waiting for `verified` (since `verified` will only resolve after reading the data). So one of a few ways to work around this is to add, at your `log(23)`,
```js
await openpgp.stream.readToEnd(decryptedMessage.getLiteralData());
```
(Or if you're already reading the data somewhere else, perhaps move that code over there instead.)

Alternatively, it might be more performant to, _before_ calling `verify`, find the literal data packet and set
```js
literal.data = await openpgp.stream.readToEnd(literal.data);
```
but that's a bit less clean.

Alternatively, since you've told OpenPGP.js that you don't want to stream, it should arguably just read the entire message by itself without waiting for you to do so. I believe it does in fact do this if (1) the message has a one-pass signature packet and (2) you haven't read the data yet when calling `verify`.

Fixing this in the other cases would be doable but slightly ugly as it would involve adding the same `streaming` parameter in quite a few other places. In general, the parameter wasn't really meant as a way to control the behavior of the API, but rather as an optimization for cases where (e.g.) streaming hashing is slower than hashing everything at once.

**Comment by tomholub** [comment]
Thank you! I'll try the suggestions above & close soon.

**Comment by tomholub** [comment]
It worked. But damn did the api indeed become more complicated :-/ It was worth it for the streaming, and you've done great job with it. I'm not as worried that the internal apis are harder to use, my bigger worry is that the library became harder to contribute to. I get it though, there will necessarily be more complexity when streaming is supported.

My notes, in case someone runs into this in the future.

Original, hang:
```js
const content = await openpgp.stream.readToEnd(decryptedMessage.getLiteralData());
const verifyResults = await decryptedMessage.verify(keysForVerification);
for (const verifyRes of verifyResults) {
  x.push(await verifyRes.verified); // hang
}
```

Your suggestion worked:
```js
const verifyResults = await decryptedMessage.verify(keysForVerification); // verify first
const content = await openpgp.stream.readToEnd(decryptedMessage.getLiteralData()); // read data second
for (const verifyRes of verifyResults) { // await results third
  x.push(await verifyRes.verified);
}
```

**Comment by twiss** [comment]
> my bigger worry is that the library became harder to contribute to

Yeah, I completely agree, I started worrying about this as well. These kinds of issues are incredibly difficult to debug if you don't already know what the library is doing and in what order. I don't know a good solution to this, but we could do a better job documenting this stuff, at least.
