### ISSUE TITLE
Session key decryption failed when decrypt file.

### ISSUE THREAD

**Issue by iamjinme** [openpgpjs/openpgpjs#923]
I encrypted a file with command `gpg --encrypt --recipient ID hello.txt`, but when I try to decrypt the file .gpg I received an error. Passphrase is not used. The code is:

```
const openpgp = require('openpgp');
const fs = require('fs');

const run = async () => {

const pubkey = fs.readFileSync('test.pub.asc').toString('ascii');
const privkey = fs.readFileSync('test.priv.asc').toString('ascii'); 

// hello.txt: "Hello World"

const buffer = fs.readFileSync('hello.txt.gpg');

const message = new Uint8Array(buffer);

const text = await openpgp.util.Uint8Array_to_str(message);

const options = {
  message: openpgp.message.fromText(text),    // parse armored message
  publicKeys: (await openpgp.key.readArmored(pubkey)).keys, // for verification (optional)
  privateKeys: (await openpgp.key.readArmored(privkey)).keys   // for decryption
}

console.table(options);

const decrypted = await openpgp.decrypt(options);

console.log(decrypted);

};

run();
```

What I should send to create a message? a Buffer, an Unit8Array or String?

**Comment by twiss** [comment]
> ```
>   message: openpgp.message.fromText(text),    // parse armored message
> ```
You probably need instead:
```js
  message: await openpgp.message.read(message),    // parse message
```
(Or passing the buffer to that function directly should also work.)

**Comment by AG-Labs** [comment]
Hi I am struggling to read in a gpg encrypted file.
I have successfully decrypted an ascii armored version of my file but my use case would be to decrypt a file, I have changed my code but I cannot get the original data back. i have also used code detailed in these issues: 
https://github.com/openpgpjs/openpgpjs/issues/906
https://github.com/openpgpjs/openpgpjs/issues/754
but still no luck, is there anything obvious that i am doing incorrectly. 


```
fs.readFile("../../test/encrypted.csv.gpg", "utf8", function (err, file) {
  if (err) {
    console.log(err);
    return;
  }
  console.log(file);
  main(file);
});

async function main(inputData) {
  let privateKey = fs.readFileSync("../../test/exportKey.pgp");

  try {
    let decryptedMessage = await decrypt(inputData, privateKey);
    console.log(decryptedMessage);
  } catch (err) {
    console.log(err);
  }
}

let decrypt = async (encryptedData, pKey) => {
  await openpgp.initWorker({ path: "openpgp.worker.js" });

  const {
    keys: [privateKey]
  } = await openpgp.key.readArmored(pKey);

  const text = await openpgp.util.Uint8Array_to_str(encryptedData);

  let myMessage;
  try {
    myMessage = await openpgp.message.read(text);
    console.log("\n\n-----message----\n\n");
    console.log(myMessage);
  } catch (err) {
    console.log("failed at reading");
    console.log(err);
  }
  try {
    let decrypted = await openpgp.decrypt({
      message: myMessage,
      privateKeys: [privateKey]
    });
    return decrypted;
  } catch (err) {
    console.log("failed at decryption");
    console.log(err);
  }
};

```

of which my current output is
`failed at reading
Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.
    at Object.read `

Obviously the second try catch block also fails but that would be due to the failure to read the message in the first

I can successfully decrypt the same file using the gpg tool in bash so i know it is valid. Am i attempting to read the file incorrectly?

**Comment by twiss** [comment]
Hey :wave:
Are the message and key armored, or are they binary files?
If they are armored,
- You should pass `"utf8"` (or `"ascii"`) to `readFile`/`readFileSync` in both cases
- You should use `readAmored` in both cases

If they are binary,
- You shouldn't pass `"utf8"` in either case
- You should use `read` in both cases.

In either case,
> ```
>   const text = await openpgp.util.Uint8Array_to_str(encryptedData);
> ```
this shouldn't be necessary.

**Comment by AG-Labs** [comment]
Thanks for the swift response.

They were binary, ive removed utf8 from fs.readfile(). and its worked.
I was under the impression that utf8 was the default so it never crossed my mind to remove it. A quick search seems to suggest it is but since the problem is fixed i will chase down what is actually happening with readfile in the morning.

Thank you very much @twiss
