### ISSUE TITLE
openpgp.verify seems to be synchronous

### ISSUE THREAD

**Issue by Tilogorn** [openpgpjs/openpgpjs#959]
I recently noticed that my Node.js main thread stops executing during `openpgp.verify`. My code is completely asynchonous. I wrapped it in a webserver, so I can track "responsiveness" by polling another HTTP endpoint.

See the following MWE. Note: I removed the error- and result handling completely to keep the example small.

```js
// Imports
var express = require('express');
var app = express();
var http = require('http').Server(app);
var fs = require('fs');
var openpgp = require('openpgp');

// Polling Endpoint
app.get('/', function (req, res) {
    res.send('OK');
});

// Verify-Endppoint
app.get('/start_openpgp', function(req, res) {
    fs.readFile('./signed_file.gpg', function (err, data) {
        fs.readFile('./public_key.gpg', function (err, pubKeyPortalBin) {
            var key = openpgp.key.read(pubKeyPortalBin);
            var message = openpgp.message.read(data);

            var options = {
                message: message,
                publicKeys: key.keys
            };

            openpgp.verify(options).then(function (verified) {
                res.send('OK');
            });
        });
    });
});

// Start Server
http.listen(3006, function () {
    console.log('Server listening on 3006');
});

```
I wrote a small script for calling the polling endpoint in a loop

```sh
#!/bin/bash

for ((i=1;i<=100000;i++));
do   echo $(date +%s%N); curl -m 0,5 localhost:3006
echo
done
```
In a second terminal I call the verifying endpoint

```sh
$ curl localhost:3006/start_openpgp
```
After starting the small script, I get successful curl calls until I call the verifying endpoint. Exactly during `openpgp.verify` curl gets timeouts. After it finished verifying curl is successful again.

```
1567415400007787940
OK
1567415400022783674
OK
1567415400035859128
OK
1567415400050457438
OK
1567415400065324147
OK
1567415400096180644
OK
1567415400110303954
curl: (28) Operation timed out after 500 milliseconds with 0 bytes received

1567415400624941602
curl: (28) Operation timed out after 502 milliseconds with 0 bytes received

1567415401134300480
curl: (28) Operation timed out after 500 milliseconds with 0 bytes received

1567415401642761432
curl: (28) Operation timed out after 501 milliseconds with 0 bytes received

1567415402151794612
curl: (28) Operation timed out after 500 milliseconds with 0 bytes received

1567415402660365788
curl: (28) Operation timed out after 502 milliseconds with 0 bytes received

1567415403170220713
OK
1567415403588755027
OK
1567415403602991706
OK
```

I am using the following versions
- openpgp.js: 3.1.3 (cannot use v4 because of older key support)
- Node.js: 8.16.1

So it seems openpgp.js is blocking my main thread which it shouldn't. Am I doing something wrong here or are the openpgp-internal synchronous calls blocking my main thread?

**Comment by twiss** [comment]
Hey :wave: All JavaScript code runs on the main thread by default, regardless of whether the function you're calling is synchronous or asynchronous. Functions like `fs.readFile` were specifically written to do the bulk of the work off the main thread, but that's not automatic. So this is more of a feature request than a bug report. There are sort of two possible routes to fix this:

- We use Node's built-in crypto functions, you could argue that it is those functions that shouldn't block the main thread: https://github.com/nodejs/node/issues/678. Mentioned there are also some modules which fill this gap that we could use, such as https://github.com/ronomon/crypto-async.

  The main disadvantage of this approach is that it doesn't do _all_ of the work off the main thread, just the crypto calls. Still, those should be the bulk of the work.

- In the browser, we use Web Workers to do work off the main thread. In Node, we could use [worker threads](https://nodejs.org/api/worker_threads.html) to achieve the same thing. You could also use a Web Worker polyfill, e.g. https://github.com/pgriess/node-webworker.

  The main disadvantage of this approach (that our current workers have as well) is that key objects aren't shared between the main thread and workers, but copied, so that certain things that could be cached (like key fingerprints) aren't. Instead, they're computed over and over.

If you're stuck with OpenPGP.js 3, the last option (Web Worker polyfill) is probably the most realistic. You might even be able to load it globally before loading OpenPGP.js, and then use `openpgp.initWorker` as usual.

A (somewhat unrelated) note of warning, though, there have been two security releases since then (see [v4.2.0](https://github.com/openpgpjs/openpgpjs/releases/tag/v4.2.0), [v4.3.0](https://github.com/openpgpjs/openpgpjs/releases/tag/v4.3.0), and https://sec-consult.com/en/blog/advisories/multiple-vulnerabilities-in-openpgp-js/). Please check whether any of the vulnerabilities affect you.

**Comment by Tilogorn** [comment]
Hey twiss,

thanks for your fast and kind reply. I get your point and will evaluate on your possible solutions. 

As this is no bug on your side, I feel free to close this issue.
