### ISSUE TITLE
Stream decryption with Web Worker: ArrayBuffer at index 0 is already neutered

### ISSUE THREAD

**Issue by descampsk** [openpgpjs/openpgpjs#995]
Hello ! 

I'm trying to decrypt a file with stream but I got the following error : 

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': ArrayBuffer at index 0 is already neutered.
    at MessagePort.c.onmessage
```

Here is my code : 

```
const response = axios.get(AWS_S3_URL, { responseType: 'blob' })
const fileData = response.data // This is a blob
const fileStream = fileData.stream() // Chrome function to convert blob into a stream
const optionsDec = {
    message: await openpgp.message.read(fileStream, true), //Here is the issue apparently
    privateKeys: [pgpData.decryptedPrivateKey],
    format: 'binary'
}
const decrypted = await openpgp.decrypt(optionsDec)
const plaintext = await openpgp.stream.readToEnd(decrypted.data)
return new File([plaintext], fileName, { type: fileType, lastModified: Date.now() })
```

I google a bit what is neutered, but I didn't understand what it really is and why I get this error.

Do someone have already see this error ?

Thank you !

**Comment by descampsk** [comment]
OK...
When i do : 

`await openpgp.message.read(fileStream, false)`

No idea what is the difference...

**Comment by descampsk** [comment]
My bad: when I use 'false', it doesn't decrypt as a stream...

I have to use this : 

`await openpgp.message.read(fileStream, true)`

Any idea of how to fix my issue ?

**Comment by descampsk** [comment]
My code is right. Because when i don't use the web worker, it works.

It's then a Web Worker issue...

**Comment by twiss** [comment]
Hey :wave: I see, I didn't know you were processing the file from the network instead of from a file on disk. That changes things. The way you're doing it now, you're not processing the network response as a stream. The `Blob` that you're getting holds the entire response in memory.

To get a stream from a response, you can simply do

```js
const response = await fetch(AWS_S3_URL);
const stream = response.body;
```

(Whether this is possible using the `axios` library you're using I don't know.)

Do you still get the error if you do that?

If so, you may be right that there's a bug. However, using the Worker in combination with streams is inefficient and not recommended. Instead, I'd recommend to create a Worker yourself, and then request the file from the network _inside_ the Worker, and pass the stream (and keys) to OpenPGP.js directly there. That avoids having to copy data back and forth. See: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers.

**Comment by descampsk** [comment]
I tried with the fetch API, but unfortunately, it doesn't work.

Here is my code : 

```
  const responseFile = await fetch(s3Url)
  const encryptedStream= responseFile.body
  const optionsDec = {
    message: await openpgp.message.read(encryptedStream, true),
    // publicKeys: (await openpgp.key.readArmored(publicKeySender)).keys, // for verification (optional)
    privateKeys: [pgpData.decryptedPrivateKey],
    format: 'binary'
  }
  const decrypted = await openpgp.decrypt(optionsDec)

  const reader = openpgp.stream.getReader(decrypted.data);
  let decryptedFileData = []
  while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (progressJson) {
        progressJson.loaded += value.length
      }
      decryptedFileData.push(value)
  }

  return decryptedFileData
```

Same error with the web worker:
![image](https://user-images.githubusercontent.com/22590202/67303912-662d8400-f4f3-11e9-886d-f570aae11513.png)

**Comment by twiss** [comment]
It's not really recommended anymore in any case, see #964. However, when streaming specifically, we have to send a message to and from the worker for _each chunk_. That's why it's more efficient to do everything in the worker.

If so, do you have `openpgp.config.zero_copy = true` set, by any chance? If so, that might be causing it. If not, I don't really understand how this error could happen. Are you using the latest version of OpenPGP.js?

**Comment by descampsk** [comment]
I update my version to the last version of openpgp which seems to be 4.2.6. But I have the same error.

When I set  openpgp.config.zero_copy = true, nothing work with the worker.
When I set openpgp.config.zero_copy = false,

I have a similar error : 
![image](https://user-images.githubusercontent.com/22590202/67332793-ccc89700-f51f-11e9-8823-b01c7bd34682.png)

I will try to use my own worker to see if it works. And you say it will be better to have my own anyway :)

**Comment by twiss** [comment]
> When I set openpgp.config.zero_copy = false, I have a similar error :

Hmm. Setting it to false shouldn't make a difference (that's the default), so if you're getting a different error, it might be random, based on a race condition.

Could you perhaps use `openpgp.js` instead of `openpgp.min.js`, and post a full stack trace of that last error, to aid debugging?

> I will try to use my own worker to see if it works. And you say it will be better to have my own anyway :)

:+1:

**Comment by descampsk** [comment]
Ok I made a mistake when updating openpgp.
I did it right and I have no error now ^^. So i will close this issue. Thanks

I'm trying to implement my own WebWorker now but I have an issue with encrypting data and the random generator. I will open a new one.
If you have some time to look it, it will be a pleasure ! :)
